### ISSUE TITLE
Incorrect behaviour when right clicking with dark steel tools

### ISSUE THREAD

**Issue by CrazyPants** [CrazyPants/EnderIO#1148]
<tterrag> CrazyP: I've come across an issue
<tterrag> DS tools right click function is being done on items it shouldn't be
<tterrag> we should be using the ItemInWorldManager
<tterrag> not directly calling onItemUse
<CrazyP> sounds fair
<CrazyP> what is the current issue actualy doing?
<tterrag> CrazyP: ex it's calling the right click function of a wireless terminal from AE2
<tterrag> which is...not working
<tterrag> it basically just freezes your controls
<CrazyP> I see
<CrazyP> that is bad

**Comment by tterrag1098** [comment]
This was fixed with https://github.com/CrazyPants/EnderIO/pull/1695
