### ISSUE TITLE
Fluid conduits connecting to Aappled Energistics cables

### ISSUE THREAD

**Issue by lehjr** [CrazyPants/EnderIO#1179]
For some reason, EnderIO fluid conduits try to connect to AE cables and anchors. This doesn't really seem to have any side effects other than visual appearance. 
![2014-11-01_19 55 23](https://cloud.githubusercontent.com/assets/1084367/4873735/a8fabe38-6222-11e4-8ae4-5db04ce75cc4.png)

**Comment by tterrag1098** [comment]
Unfortunately because AE2 implements IFluidHandler on their cables, this is not fixable without a hardcoded check, sorry.
