### ISSUE TITLE
ME Conduits don't work properly with the ME Security Terminal

### ISSUE THREAD

**Issue by MrMetric** [CrazyPants/EnderIO#1227]
If I add a security terminal to my network and exclude build from the default permissions, ME Conduits get all screwy. Placing them usually causes adjacent parts of the network to break, and connections do not always work. Example: the left panel is on, but right panel is not:
<img src="http://i.imgur.com/5CSnoOA.png">

Info, just in case it's useful:
 - Ender IO version = 2.1.8.269
 - Applied Energistics 2 version = rv2 alpha 16
 - Forge version = 10.13.2.1235
 - I have > 100 other mods installed

**Comment by tgstyle** [comment]
When using a security terminal, you can put in a blank card with build permissions to fix it. Conduit doesn't have the right security permissions in it yet (my guess).

**Comment by tterrag1098** [comment]
Fixed for the next version
