### ISSUE TITLE
Travel Anchors acting Weird based on if looking at the bottom or top of them!

### ISSUE THREAD

**Issue by kurokuno** [CrazyPants/EnderIO#1380]
what i mean is when going up from under an anchor if your looking at the outside of the box it sometimes does not highlight however going down this issue seems to be non existent 

in this example i am using them as up/down elevators directly under/above each other separated by 4 blocks

**Comment by tterrag1098** [comment]
The top block in those screenshots is much closer to your face, the target size is still the same.
