### ISSUE TITLE
Crash when breaking Mekanism UE cables connected to capacitor bank 

### ISSUE THREAD

**Issue by PsionicArchon** [CrazyPants/EnderIO#1433]
As the title suggests, Mekanism's UE cables aren't playing nice with EnderIO.

Crash: http://pastebin.com/bWbgFzaq

This was tested in single player and on my server.

Mekanism version: 7.1.1.142
EnderIO: 2.2.4.309
Forge: 10.13.2.1264
cofhlib: CoFHLib-[1.7.10]1.0.0B8-34

I have removed the cofh folders from all install mods in an attempt to get rid of any out dated api's. This did not prevent the crash. 

I'm not sure whose end this is on as Mek cables work with other RF producers. 

Edit: Removed every mod accept for EnderIO and Mekanism. The crash still happens. 

My report on the Mekanism github: https://github.com/aidancbrady/Mekanism/issues/2037

**Comment by fwsGonzo** [comment]
Can confirm

**Comment by mrdeadlocked** [comment]
Can confirm
