### ISSUE TITLE
Issue with conduit facade connecting textures

### ISSUE THREAD

**Issue by PirateToshio** [CrazyPants/EnderIO#1478]
Small issue with the conduit facade's, I haven't been able to test all the blocks but the connected textures doesn't wrap to non-conduit facade blocks if it is painted as a "Weared Metal Column" from Chisel 2, but if painted as say a "Wireframe", "Rusty Metal Plate" or "Fancy circuit block with gold plating" the the connected textures work fine.

 ( http://minecraft.curseforge.com/mc-mods/225236-chisel-2 )

**Comment by ShadwDrgn** [comment]
I have this with factory blocks. all varieties i believe. the textures just don't connect :~(

**Comment by tterrag1098** [comment]
Update chisel

**Comment by ShadwDrgn** [comment]
I'm on the newest chisel.

**Comment by tterrag1098** [comment]
Use chisel 2, not the old unsupported chisel.

http://curse.com/project/225236

**Comment by rashdanml** [comment]
Well, as of Chisel2-2.3.5.31 (which is a fairly recent release), the problem still exists. I'll try to see if I can get it updated on our server.
