### ISSUE TITLE
ME Conduit sometimes connects to ME cable without showing a Conduit Connector

### ISSUE THREAD

**Issue by weswigham** [CrazyPants/EnderIO#1487]
![Screenshot of bug](http://puu.sh/dIcP1/d2fcc63e98.jpg)

This seems to occur somewhat reliably alongside #1227 (I, too, happen to be using a security terminal with no permissions for the default user) - usually when you place a conduit if it breaks the neighboring cable, when you replace said cable it doesn't create a conduit connector (but appears to connect and function).

I happened to notice this running the Direwolf20 (for 1.7) 1.0.3 modpack, which contains EnderIO version 1.7.10-2.2.5.311, and applied energistcis 2 version rv2-beta-1.

**Comment by tterrag1098** [comment]
This has been fixed for the next version
