### ISSUE TITLE
ME conduit incorrectly reporting "number installed" on ME network

### ISSUE THREAD

**Issue by Rosethorns** [CrazyPants/EnderIO#1518]
Here I have a screen shot example of the problem, under the floor there are about 80 ME conduits and 60 ME dense conduits.

However the ME network is reporting numbers incorrectly. As you will see in the screenshot this network believes there are 37,000 Dense ME conduit installed and doesn't even see the ME conduit.
(however the line connected by ME conduit is still functioning) 

As you will also see the Network truly believes that 37k dense conduit is truly installed and the energy usage reflects that.

Screenshot: http://i.imgur.com/jVA6lyL.png

**Comment by tterrag1098** [comment]
This has been fixed for the next version
