### ISSUE TITLE
ME Network takes a very long time to establish when using ME Conduit types

### ISSUE THREAD

**Issue by Rosethorns** [CrazyPants/EnderIO#1519]
This issue is possibly connected to #1518 

A network which uses ME conduit types takes are very very long time to "establish" (entering the unloaded chunks e.t.c) so while parts of the network are seen as "online" you will not be able to access their contents for anywhere from 30 seconds to 3 minutes.

These issues go away when you swap the conduit out for AE cable

**Comment by tterrag1098** [comment]
This has been fixed for the next version
