### ISSUE TITLE
ME conduits break AE2 cables

### ISSUE THREAD

**Issue by deadgamer1030** [CrazyPants/EnderIO#1520]
when ever i place a ME conduit ( normal or dense) onto a network that is being p2p`d it will break the me cable and will also break ME controllers. If the network is not p2p`d it will be fine. If you later add a p2p tunnel to it, it will not update the conduit texture ( the little square bit)  and if you remove an adjacent AE2 cable from it, it will remain if it was still connected and if it is placed back then the cable will pop off.
 I am using a modified version of the direwolf 1.7.10, with up to date enderio and applied energistics.

**Comment by Cobra1117** [comment]
Also getting this bug. Relevant version numbers:
Forge: 10.13.2.1277
Applied Energistics: 2 RV2 Beta 7
Ender IO: 2.2.6.317

**Comment by tgstyle** [comment]
I have conduit on a P2Pd network working fine, I run it off of regular dense/smart cable where needed coming from a controller. The only time I have it break, is if I have a security terminal. If using a security terminal, you can put in a blank card with build permissions to fix it. Conduit doesn't have the right security permissions in it yet (my guess).

https://github.com/CrazyPants/EnderIO/issues/1227

**Comment by tterrag1098** [comment]
This has been fixed for the next version
