### ISSUE TITLE
Power monitor goes in minus when having huge machine capacities

### ISSUE THREAD

**Issue by zlepper** [CrazyPants/EnderIO#1541]
Just a heads up that the power monitor doesn't like very big values ;)

![selection_014](https://cloud.githubusercontent.com/assets/1499810/5587782/5a8c1466-90f5-11e4-8d45-09180085f85f.png)

**Comment by hilburn** [comment]
should be solved by #1545 - it uses a long rather than an int for the machine buffers which should prevent this kind of overflow
