### ISSUE TITLE
Support for Blood Magic Sacrificial Dagger in Killer Joe

### ISSUE THREAD

**Issue by zlepper** [CrazyPants/EnderIO#1546]
Would enable to nice automation, which there really isn't a lot of right now. Only the sacrificial ritual thingy I can't remember what's called.

**Comment by hilburn** [comment]
This would utterly break what little semblance of balance that Blood Magic has, at least to automate it currently with the ritual you have to progress in the mod, this would bypass a huge amount of the mod's mechanics and generally ruin everything

**Comment by zlepper** [comment]
No need to implement it then.
