### ISSUE TITLE
Conduit facade is unbreakable in Adventure Mode

### ISSUE THREAD

**Issue by Nargon** [CrazyPants/EnderIO#1549]
I play minecraft in adventure mode (gregtech - hard) and i found a bug with the Conduit facade. This block is unbreakable. The pickaxe, axe, shovel, sword or empty hand can't mine this block. Right click with wrench is impossible, because when you have wrench in hand the conduit facade is invisible.
Only the TNT can destroy the conduit facade. Other "painted" blocks (glowstone, fence, etc...) is breakeable with axe or pickaxe, but only the conduit facade has this bug.

Can you set a proper material to conduit facade? Or add a pickaxe as tool for breaking this block.

**Comment by tterrag1098** [comment]
Not marking this as a bug, because it isn't really, but I do agree that pickaxes working on facades/machines would be nice.
