### ISSUE TITLE
Farming station flux tools support

### ISSUE THREAD

**Issue by zlepper** [CrazyPants/EnderIO#1551]
Can support for the Flux tools from Redstone Arsenal be added, so the farming station can use them?

Specifically the shovel, which can act as a hoe. And the axe, which can act as, you guessed it: an axe. 

Hope you can implement this :)

Edit also, support for magical crops hoes? the level 3 one is supposed to be unbreakable, but isn't in the farming station.

**Comment by tterrag1098** [comment]
In 2.2.6 this should work. You can even whitelist your own hoes.
