### ISSUE TITLE
Ticking entity crash after update to 1.7.10-2.2.6.317

### ISSUE THREAD

**Issue by nukeofwf** [CrazyPants/EnderIO#1552]
http://pastebin.com/zQhvx2dV

Ticking entity appeared after version update.
Not 100% certain of cause.
From the 1.7.10 pack on technicpack

**Comment by Cobra1117** [comment]
This is a bug with ME conduits. I turned on the "remove erroring tile entities" setting in forge, and any time I place an ME conduit it throws an exception and the conduit is removed from the world.

**Comment by Cobra1117** [comment]
Note: Bug also applies to Dense ME Conduiits

**Comment by tterrag1098** [comment]
>        appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available

>- **REMOVE AE2 rv1 SUPPORT COMPLETELY**

**Comment by Cobra1117** [comment]
Hrm. Missed that somehow. Derp. Thanks!
