### ISSUE TITLE
Fluid conduit has no input color?

### ISSUE THREAD

**Issue by tgstyle** [CrazyPants/EnderIO#1553]
You can set a color on extract, but not on input. I am using ender fluid conduit.

Build 317.

**Comment by tterrag1098** [comment]
What? Why would you need a color on input?

**Comment by tgstyle** [comment]
You have color on the output, but it has no where to go for input.

**Comment by tgstyle** [comment]
Unless I am mistaken, what is the need for color on extract then?

**Comment by tterrag1098** [comment]
The color is the color of redstone signal it responds to. Input needs no redstone signal so it doesn't have a color option.

**Comment by tgstyle** [comment]
Haha OK, I am cracking up. Too much candy over the holidays. However I do have a scenario for color needs. If you have an extra cells fluid interface. if you are trying to do outputs on each side and one side input it can cause a loop.

**Comment by tgstyle** [comment]
Filters can help but not if you are trying to input lava on one side, output on the other and have those conduits connected.
