### ISSUE TITLE
solar dark steel helmet doesn't notice jetpacks armor

### ISSUE THREAD

**Issue by seebs** [CrazyPants/EnderIO#1555]
The Dark Soularium Jetplate is sort of EIO-based armor, and could be recharged, but isn't. It'd be neat if it (and their other stuff like capacitor packs, lower-tier jet packs, etc.) got recharged by the solar helmet.

**Comment by tterrag1098** [comment]
This should be fixed via https://github.com/CrazyPants/EnderIO/commit/9fa3d5d6456d14349b77a7dec497cf29a2aed238
