### ISSUE TITLE
Farming Station tool slots are not honoring axe/hoe.

### ISSUE THREAD

**Issue by tgstyle** [CrazyPants/EnderIO#1556]
Either slot takes either tool. This is causing issues trying to have a farming station do normal farms and wood together.

Build 317.

**Comment by tterrag1098** [comment]
I could not implement this strictly as asked because there are more than 2 types of tools that can go in the station. As it is implemented now the farm will take ONE of any tool type, regardless of the slot.

**Comment by tgstyle** [comment]
Nice, thanks!
