### ISSUE TITLE
Add core file warnings to all files

### ISSUE THREAD

**Issue by 6210classick** [CrazyPants/EnderIO#1559]
each time i launch the game EnchanterRecipes_Core keep going back to it's default setting

this a modified EnchanterRecipes_Core by me
https://www.dropbox.com/s/2w8nh9op9m5xmw2/EnchanterRecipes_Core.xml?dl=0

Forge version : 10.13.2.1277
EIO version 2.2.6.317

**Comment by tterrag1098** [comment]
Core files are not meant to be edited, use the user files.

**Comment by 6210classick** [comment]
so if i want to change some of the recipes from the core do i have to enter them in user files ? isn't there gonna be a conflict ?

**Comment by 6210classick** [comment]
so if i want to change some of the recipes from the core do i have to enter them in user files ? isn't there gonna be a conflict ?

**Comment by Xaw4** [comment]
it's either going to be overwritten or added (depending on how you named the recipes in the xml)
