### ISSUE TITLE
Farming station not accepting wooden axe.

### ISSUE THREAD

**Issue by kokono2** [CrazyPants/EnderIO#1561]
The farming station doesn't accept wooden axes anymore since I updated to 1.7.10-2.2.6.317. It does accept wooden hoes and every axe better than wood.

**Comment by tterrag1098** [comment]
If you have a mod which modifies the vanilla tools so that they can't mine
trees it won't work.

**Comment by kokono2** [comment]
I haven't added new mods since I updated to the version of EnderIO in previous post. Mining wood with the wooden axe works perfectly fine.
