### ISSUE TITLE
powered spawner config server

### ISSUE THREAD

**Issue by mirkaria** [CrazyPants/EnderIO#1562]
Hello there my friend has a server and we whould really like to whitelist villagers but no matter what he tried it just won't let me put the vial in the soul binder any ideas? we tried changing the user and the core it also doesn't work in single player

**Comment by hilburn** [comment]
Replace the PoweredSpawnerConfig_User.json with the following: [PoweredSpawnerConfig_User.json](http://puu.sh/dZZSn/ec6d673202.json) - works fine for me

**Comment by jmcaffee** [comment]
I had this problem as well. Updating to 2.2.6.317 and using the config posted above (downloaded with curl) made no difference.

Updating the **local** version of PoweredSpawnerConfig_User.json **as well as the server's version** allowed it to work.

**Comment by hilburn** [comment]
Ah ok - in that case, yeah, use consistent configs... 
I will look into seeing if there's a way to either sync clients to dedicated servers or at least notify players if their config settings are inconsistent with the server's
