### ISSUE TITLE
Bug with Farming Station

### ISSUE THREAD

**Issue by chitown3** [CrazyPants/EnderIO#1569]
So I'm playing the SkyFactory2 modpack and and currently the configs for magical crops are so that seeds do not drop upon harvesting them. Placing a vanilla hoe works as intended but as soon as I place a tinkers mattock in the farming station , plants begin to drop seeds. Not sure if this is on your end or magical crops end

**Comment by 6210classick** [comment]
use the Vacuum chest to suck the seeds then pipe it back to the farming station with item conduits

did you tried other hoes from other mods ? it's probably how TC hoe behaves

**Comment by chitown3** [comment]
Yes thank you for the suggestion but I think you misunderstood me. The magical crops config is set to Not drop seeds meaning if you want seeds you have to craft them individually rather than having a chance to drop a seed

**Comment by tterrag1098** [comment]
Magical crops' implementation is bad, and they are dropping extra items when passed a fortune modifier. Your mattock has luck on it, I'm guessing?
