### ISSUE TITLE
ME Conduit multiblock crash

### ISSUE THREAD

**Issue by eastpunk** [CrazyPants/EnderIO#1572]
When placing a ME Conduit 4727, the game crashes.

Recreated in a test world as well.

EnderIO-1.7.10-2.2.6.317

**Comment by MinoCraft** [comment]
Hello,
When I update my pack with the last version of Ender IO (1.7.10-2.2.6.317), the game crash.
The problem is about ME Conduit.
You can see the crash report here:
https://www.dropbox.com/s/bawi3of4b9ihhp5/crash-2014-12-31_23.56.51-server.txt?dl=0
Thanks in advance !

**Comment by tterrag1098** [comment]
Update AE2 to rv2, rv1 is no longer supported.
