### ISSUE TITLE
Openning Configure IO in Farming Station Crash

### ISSUE THREAD

**Issue by MinoCraft** [CrazyPants/EnderIO#1578]
Hello,

When I click for configure IO in the farming station the game crash :/
I use Ender IO 1.7.10-2.2.4.309
You can see the crash report here:
https://www.dropbox.com/s/cettlgx29sebpf0/crash-2015-01-04_19.56.14-client.txt?dl=0

Thanks in advance !

**Comment by tterrag1098** [comment]
This was fixed ages ago, update please.
