### ISSUE TITLE
[Stirling Generator] ComputerCraft,  getPowerPerTIck()

### ISSUE THREAD

**Issue by norfair** [CrazyPants/EnderIO#1587]
Hello,

When I call the function getPowerPerTIck() I error "lua:1: bad argument: table expected, got function

**Comment by Vexatos** [comment]
I assume you have Computronics installed, it is most likely an issue with that mod, I will take a look at it.

**Comment by Vexatos** [comment]
Ah, right, this has already been fixed. Just wait for the next version of Computronics, sorry for the inconvenience.
