### ISSUE TITLE
Minecraft crashes when I connect an Energy Conduit to a TE4 Energy Cell

### ISSUE THREAD

**Issue by ArkhamNightmare** [CrazyPants/EnderIO#1589]
As the title says, whenever I connect an Energy Conduit to a Thermal Expansion 4 1.7.10 Energy Cell ( any of them ) the game crashes! I hope that you can find the source of the problem and fix it soon.

**Comment by TheJulianJES** [comment]
Crash-Report, Logs, Versions?

**Comment by iTitus** [comment]
See #1584 and many many others
