### ISSUE TITLE
Support the IInventoryConnection (CoFH) APIs

### ISSUE THREAD

**Issue by asiekierka** [CrazyPants/EnderIO#1596]
https://github.com/CrazyPants/EnderIO/blob/52fe7c9e10168da4c3b80a850a18e9cff4759868/src/main/java/crazypants/enderio/conduit/item/ItemConduit.java#L547-L552

This is to remove the need for the nasty hack above.

**Comment by asiekierka** [comment]
(If you really want to, you could also add support for conduits to use IInjectable from BC - which is coming in 6.3.0)

**Comment by tterrag1098** [comment]
Fixed in https://github.com/hilburn/EnderIO/commit/e3e707bd0a8ecf15baa171f7d8c24372dbec96d4
