### ISSUE TITLE
ME terminal backwards on ME conduit

### ISSUE THREAD

**Issue by bountyhog** [CrazyPants/EnderIO#1597]
Still functional, but not very aesthetically pleasing. Trying to attach a crafting terminal to an ME conduit results in it facing away from the player, making it impossible to turn the right way.

Also tested with the other terminal types, same result.

![me terminal](https://cloud.githubusercontent.com/assets/10386936/5628430/1927a926-95fb-11e4-920d-29bf01e3fd62.jpg)

**Comment by iTitus** [comment]
This is beacause you cannot place those AE parts on ME conduits. You need a cable from AE in between.

**Comment by tterrag1098** [comment]
Not a bug, the terminal is not connecting because conduits are not multiparts. This is intended.
