### ISSUE TITLE
Painted Travel Anchor crash

### ISSUE THREAD

**Issue by Granik24** [CrazyPants/EnderIO#1600]
Hi. I have problem with Travel Anchor. 
Player on my server painted Travel Anchor to Grass Block. With that, all is fine. After a while he decided to recolor it back. He put Grass Block (Travel Anchor) and no-painted Travel Anchor to Painting Machine. After that, he used that Travel Anchor and client-side still crashing game. With server is all fine.
Any solutions?

Here is crash report: http://pastebin.com/mrVxa4VM

**Comment by Granik24** [comment]
Updated to latest version, still, same crash..

**Comment by Granik24** [comment]
So, do you have any idea, where can be a problem?

**Comment by tterrag1098** [comment]
You need to delete the anchor from your world somehow. Its data is
corrupted. This issue will not happen again but I cannot fix the existing
one.

**Comment by Granik24** [comment]
@tterrag1098 Thanks, fixed.
