### ISSUE TITLE
[Omni Buffer] Redstone Mode is shown as Configure IO when moused-over

### ISSUE THREAD

**Issue by VictiniX888** [CrazyPants/EnderIO#1609]
![2015-01-07_20 38 15](https://cloud.githubusercontent.com/assets/9777462/5645633/543a0178-96ad-11e4-9ab0-ee0d0374fb1f.png)
Tested with 2.2.6.317

**Comment by tterrag1098** [comment]
Odd. Thanks.

**Comment by tterrag1098** [comment]
Marking with proper labels. @MatthiasMann don't use "fixes #xxx" in the commit msg as that actually closes the issue.
