### ISSUE TITLE
Feature Request - Dimensional Tranciever Redstone?

### ISSUE THREAD

**Issue by ShadowsVengeance** [CrazyPants/EnderIO#1614]
The Dimensional Transceiver is truly a work of art, it does so many things. I think it could also be cool if it could send Redstone signals as well. What would be even cooler (and maybe too powerful) is if it could accept all colors of redstone signal from the Insulated conduits and send a signal to another transceiver based on what color the it recieves (if that makes any sense). Or maybe emit the same color from the receiving end. This could obviously be done with other mods, but I think it would be awesome. I'm sure you guys will be able to come up with other awesome ideas on the subject.

Obvious Case: Having a control room with a bunch of levers connected to insulated redstone conduits tied to a transceiver to turn machines off.

Case 1: Farming station and ME Level Emitter. 1-2 Transceivers send axes, power; receive items, and then turn off the farming station when it reaches a certain amount of logs.

Case 2: Elevator Tracks from railcraft, sending a signal to power a certain amount of rails to get to a desired level.

Thanks for being open to suggestions and thanks for the awesome mod! Keep up the great work.

**Comment by tgstyle** [comment]
A quick search or scroll down would have turned up this request.
https://github.com/CrazyPants/EnderIO/issues/1566

**Comment by ShadowsVengeance** [comment]
My apologies.
