### ISSUE TITLE
Farming Station damaging Unbreakable tools...again.

### ISSUE THREAD

**Issue by smokeluvr1971** [CrazyPants/EnderIO#1615]
Using 2.2.6-317.  TiCo axes [Hatchet and Lumber] are getting eaten from very few uses.  Vanilla Iron axe with Unbreaking X [applied via NEI] is taking damage.  Ichorium [unawakened] takes no damage [only one I've found/have access to].

**Comment by smokeluvr1971** [comment]
Little more detail on TiCo usage.  IgwanaTweaks enabled so TiCo tools weren't Unbreakable [freshly assembled], but were full Obsidian with some Obsidian plating [Reinforced VI IIRC].  Both Hatchet and Lumber axe were eaten before finishing a 2x2 Jungle tree.

**Comment by Barhandar** [comment]
Vanilla Unbreaking X is not Unbreakable, it just has very, very low chance to get damaged.

**Comment by tterrag1098** [comment]
This is fixed under https://github.com/CrazyPants/EnderIO/commit/742197ad9b7c636b5284ac4046c59e42656a2a90
