### ISSUE TITLE
Farming Station eats tinker's construct items.

### ISSUE THREAD

**Issue by Erozolis** [CrazyPants/EnderIO#1617]
In the farming station these 2 things happen when you insert tinker's items.

Expected: Tinker's construct item reads "broken" and stops working.
Actuality: Tinker's construct item gets deleted.

Other,

Expected: "unbreakable" item should not lose durability
Actuality: item loses durability

**Comment by tgstyle** [comment]
Couldn't bother to look 2 issues down? https://github.com/CrazyPants/EnderIO/issues/1615 already reported.
