### ISSUE TITLE
Vibrant Capacitor Bank dupe energy.

### ISSUE THREAD

**Issue by Tsyklop** [CrazyPants/EnderIO#1620]
If you take Vibrant Capacitor Bank and put it in your inventory it will start charging itself. Fix this pls

EnderIO-1.7.10-2.2.6.317

**Comment by abhomination** [comment]
i was trying to figure out how they were charging before i put them back down

**Comment by Tsyklop** [comment]
I give VCB from creative and it will start charging itself

**Comment by tgstyle** [comment]
Do you have a wireless charger? It will charge them before you place it.

**Comment by Tsyklop** [comment]
tgstyle. inventory clear

**Comment by tgstyle** [comment]
Not in your inventory. Have you placed this block http://wiki.enderio.com/Wireless_Charger anywhere in the vicinity?

**Comment by Tsyklop** [comment]
tgstyle: no

**Comment by Tsyklop** [comment]
this bug does not apply to mod Ender IO. But what could it be? Even if the cell from ThermalExpansion charged.

**Comment by tterrag1098** [comment]
It means there must be a wireless charger nearby. Things don't magically charge themselves.

**Comment by Tsyklop** [comment]
wireless charger was not placed in the world

**Comment by 6210classick** [comment]
tier 5 jet pack from simply jet pack mod also charges the capacitor

also what forge version are you using ? you might want to update to the latest or create a new world and see if the capacitor is charging or not

**Comment by Tsyklop** [comment]
6210classick, if generate a new world will not be a problem

**Comment by tgstyle** [comment]
Then it is obvious you have some sort of charging system set up in the area. As one of the mod devs has stated "It means there must be a wireless charger nearby. Things don't magically charge themselves." I suggest this be closed as user error.
