### ISSUE TITLE
Minecraft 1.7.10: Farm Station Crash?!?

### ISSUE THREAD

**Issue by MBfromOK** [CrazyPants/EnderIO#1624]
Minecraft 1.7.10

ok, so I am not sure what is happening, I try to start minecraft and it crashes.. the log shows a bunch of messages containing: crazypants.enderio.machine.farm.GuiFarmStation so I am hoping it is a safe bet that EnderIO is involved?

Crash report attached (Sic). 
>---- Minecraft Crash Report ----
>// I bet Cylons wouldn't have this problem.
>
>Time: 1/3/15 4:43 PM
>Description: Rendering screen
>
>java.lang.IndexOutOfBoundsException: Index: 8962351, Size: 47
>	at java.util.ArrayList.rangeCheck(Unknown Source)
>	at java.util.ArrayList.get(Unknown Source)
>	at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
>	at crazypants.enderio.machine.farm.GuiFarmStation.drawForegroundImpl(GuiFarmStation.java:55)
>	at crazypants.gui.GuiContainerBase.func_146979_b(GuiContainerBase.java:101)
>	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)
>	at crazypants.gui.GuiContainerBase.func_73863_a(GuiContainerBase.java:117)
>	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1355)
>	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
>	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
>	at net.minecraft.client.main.Main.main(SourceFile:148)
>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>	at java.lang.reflect.Method.invoke(Unknown Source)
>	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
>	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>	at java.lang.reflect.Method.invoke(Unknown Source)
>	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
>	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
>	at org.multimc.EntryPoint.listen(EntryPoint.java:165)
>	at org.multimc.EntryPoint.main(EntryPoint.java:54)
>
>
>A detailed walkthrough of the error, its code path and all known details is as follows:
>---------------------------------------------------------------------------------------
>
>-- Head --
>Stacktrace:
>	at java.util.ArrayList.rangeCheck(Unknown Source)
>	at java.util.ArrayList.get(Unknown Source)
>	at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
>	at crazypants.enderio.machine.farm.GuiFarmStation.drawForegroundImpl(GuiFarmStation.java:55)
>	at crazypants.gui.GuiContainerBase.func_146979_b(GuiContainerBase.java:101)
>	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)
>	at crazypants.gui.GuiContainerBase.func_73863_a(GuiContainerBase.java:117)
>
>-- Screen render details --
>Details:
>	Screen name: crazypants.enderio.machine.farm.GuiFarmStation
>	Mouse location: Scaled: (480, 254). Absolute: (960, 509)
>	Screen size: Scaled: (960, 509). Absolute: (1920, 1018). Scale factor of 2
>
>-- Affected level --
>Details:
>	Level name: MpServer
>	All players: 1 total; [EntityClientPlayerMP['Compugician'/85, l='MpServer', x=1345.02, y=5.62, z=-848.55]]
>	Chunk stats: MultiplayerChunkCache: 286, 295
>	Level seed: 0
>	Level generator: ID 01 - flat, ver 0. Features enabled: false
>	Level generator options: 
>	Level spawn location: World: (1358,4,-794), Chunk: (at 14,0,6 in 84,-50; contains blocks 1344,0,-800 to 1359,255,-785), Region: (2,-2; contains chunks 64,-64 to 95,-33, blocks 1024,0,-1024 to 1535,255,-513)
>	Level time: 11097 game time, 11097 day time
>	Level dimension: 0
>	Level storage version: 0x00000 - Unknown?
>	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
>	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
>	Forced entities: 35 total; [EntityWildChicken['Wild Chicken'/64, l='MpServer', x=1385.56, y=4.00, z=-860.44], EntityWildChicken['Wild Chicken'/65, l='MpServer', x=1386.41, y=4.00, z=-865.41], EntityWildChicken['Wild Chicken'/66, l='MpServer', x=1387.50, y=4.00, z=-857.50], EntityWildChicken['Wild Chicken'/67, l='MpServer', x=1384.72, y=4.00, z=-850.22], EntityClientPlayerMP['Compugician'/85, l='MpServer', x=1345.02, y=5.62, z=-848.55], EntityVillager['Villager'/23, l='MpServer', x=1310.56, y=4.00, z=-913.16], EntityVillager['Villager'/25, l='MpServer', x=1309.38, y=4.00, z=-918.25], EntityVillager['Villager'/24, l='MpServer', x=1310.78, y=4.00, z=-917.72], EntityVillager['Villager'/27, l='MpServer', x=1304.53, y=4.00, z=-898.31], EntityVillager['Villager'/26, l='MpServer', x=1301.50, y=5.00, z=-903.66], EntityVillager['Villager'/29, l='MpServer', x=1310.69, y=4.00, z=-905.00], EntityVillager['Villager'/28, l='MpServer', x=1310.16, y=4.00, z=-906.59], EntityWildSheep['Wild Sheep'/31, l='MpServer', x=1306.16, y=4.00, z=-864.66], EntityVillager['Villager'/30, l='MpServer', x=1304.75, y=4.00, z=-894.41], EntityVillager['Villager'/35, l='MpServer', x=1318.50, y=5.00, z=-919.84], EntityWildSheep['Wild Sheep'/32, l='MpServer', x=1302.34, y=5.00, z=-870.53], EntityWildSheep['Wild Sheep'/33, l='MpServer', x=1312.78, y=4.00, z=-855.78], EntityVillager['Villager'/38, l='MpServer', x=1318.34, y=4.00, z=-903.31], EntityVillager['Villager'/39, l='MpServer', x=1315.22, y=6.00, z=-907.41], EntityVillager['Villager'/36, l='MpServer', x=1323.50, y=6.00, z=-901.78], EntityVillager['Villager'/37, l='MpServer', x=1315.50, y=4.00, z=-898.75], EntityWildSheep['Wild Sheep'/42, l='MpServer', x=1316.25, y=4.00, z=-869.63], EntityVillager['Villager'/40, l='MpServer', x=1321.47, y=4.00, z=-904.66], EntityVillager['Villager'/41, l='MpServer', x=1313.31, y=4.00, z=-890.66], EntityVillager['Villager'/51, l='MpServer', x=1328.22, y=6.00, z=-910.50], EntityVillager['Villager'/50, l='MpServer', x=1330.22, y=4.00, z=-896.44], EntityVillager['Villager'/49, l='MpServer', x=1327.94, y=4.00, z=-907.69], EntityWildSheep['Wild Sheep'/48, l='MpServer', x=1346.38, y=4.00, z=-911.78], EntityWildSheep['Wild Sheep'/55, l='MpServer', x=1334.03, y=4.00, z=-880.94], EntityWildSheep['Wild Sheep'/54, l='MpServer', x=1329.03, y=4.00, z=-883.97], EntityVillager['Villager'/53, l='MpServer', x=1330.50, y=4.00, z=-895.16], EntityVillager['Villager'/52, l='MpServer', x=1331.44, y=4.00, z=-895.97], EntityWildSheep['Wild Sheep'/58, l='MpServer', x=1357.19, y=4.00, z=-896.78], EntityWildSheep['Wild Sheep'/57, l='MpServer', x=1354.22, y=4.00, z=-906.09], EntityWildSheep['Wild Sheep'/63, l='MpServer', x=1357.94, y=4.00, z=-900.03]]
>	Retry entities: 0 total; []
>	Server brand: fml,forge
>	Server type: Integrated singleplayer server
>Stacktrace:
>	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
>	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
>	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
>	at net.minecraft.client.main.Main.main(SourceFile:148)
>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>	at java.lang.reflect.Method.invoke(Unknown Source)
>	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
>	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>	at java.lang.reflect.Method.invoke(Unknown Source)
>	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
>	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
>	at org.multimc.EntryPoint.listen(EntryPoint.java:165)
>	at org.multimc.EntryPoint.main(EntryPoint.java:54)
>
>-- System Details --
>Details:
>	Minecraft Version: 1.7.10
>	Operating System: Windows 7 (amd64) version 6.1
>	Java Version: 1.7.0_60, Oracle Corporation
>	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
>	Memory: 1144671400 bytes (1091 MB) / 2348285952 bytes (2239 MB) up to 2885681152 bytes (2752 MB)
>	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx3096m -XX:PermSize=256m
>	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
>	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
>	FML: MCP v9.05 FML v7.10.85.1236 Minecraft Forge 10.13.2.1236 Optifine OptiFine_1.7.10_HD_U_B1 57 mods loaded, 57 mods active
>	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	FML{7.10.85.1236} [Forge Mod Loader] (forge-1.7.10-10.13.2.1236-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	Forge{10.13.2.1236} [Minecraft Forge] (forge-1.7.10-10.13.2.1236-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	appliedenergistics2-core{rv1-beta-37} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	MobiusCore{1.2.3} [MobiusCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	NotEnoughItems{1.0.3.76} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.76-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	SciMCLibCore{0.0.0.2} [SciMCLibCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	OpenModsCore{@VERSION@} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	debug{1.0} [debug] (denseores-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	appliedenergistics2{rv1-beta-37} [Applied Energistics 2] (appliedenergistics2-rv1-beta-37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	CoFHCore{1.7.10R3.0.0B9} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B9-41.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	ThermalFoundation{1.7.10R1.0.0RC1} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC1-13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	ThermalExpansion{1.7.10R4.0.0B8} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0B8-23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	BigReactors{0.4.0A} [Big Reactors] (BigReactors-0.4.0A.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	ForgeMultipart{1.1.1.320} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	chisel{2.1.0.1} [Chisel] (Chisel 2-2.1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	Waila{1.5.7} [Waila] (Waila-1.5.7a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	CompactMachines{1.7.10-1.12} [Compact Machines] (compactmachines-1.7.10-1.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	EnderIO{1.7.10-2.2.4.309} [Ender IO] (EnderIO-1.7.10-2.2.4.309.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	EnderTech{1.7.10-0.3.0.348} [EnderTech] (EnderTech-1.7.10-0.3.0.348.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	EnderZoo{1.7.10-1.0.5.14} [Ender Zoo] (EnderZoo-1.7.10-1.0.5.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	exnihilo{1.37} [Ex Nihilo] (Ex-Nihilo-1.37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	TConstruct{1.7.10-1.8.1.build815} [Tinkers' Construct] (TConstruct-1.7.10-1.8.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	Metallurgy{4.0.5} [Metallurgy 4] (Metallurgy-1.7.10-4.0.5.75.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	ExtraTiC{0.8.4} [ExtraTiC] (ExtraTiC-1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	ExtraUtilities{1.2.0} [Extra Utilities] (extrautilities-1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	FastCraft{1.12} [FastCraft] (fastcraft-1.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	McMultipart{1.1.1.320} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	imc{1.6} [Improving Minecraft] (Improving Minecraft-1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	IronChest{6.0.62.742} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	JABBA{1.2.0a} [JABBA] (Jabba-1.2.0a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	minechem{5.0.5.347} [Minechem] (Minechem-1.7.10-5.0.5.347.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	NEIAddons{1.12.3.11} [NEI Addons] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	NEIAddons|Botany{1.12.3.11} [NEI Addons: Botany] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	NEIAddons|Forestry{1.12.3.11} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	NEIAddons|CraftingTables{1.12.3.11} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	NEIAddons|ExNihilo{1.12.3.11} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	ObsidiPlates{3.0.0.18} [ObsidiPlates] (ObsidiPlates-1.7.10-universal-3.0.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6-snapshot-225.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3-snapshot-436.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	YogpstopLib{2.0.0} [Yogpstop Library] (QuarryPlus-1.7.10-2.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	QuarryPlus{2.0.0} [QuarryPlus] (QuarryPlus-1.7.10-2.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	SciMCLib{SciMCLib} [SciMCLib] (SciMCLib-1.7.10-0.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	StevesFactoryManager{A90} [Steve's Factory Manager] (Steves-Factory-Manager-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	TiCTooltips{1.1.11b} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.1.11b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	TMechworks{1.7.10-86.e500b88} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	WailaHarvestability{1.1.0} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	denseores{1.0} [Dense Ores] (denseores-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	ForgeMicroblock{1.1.1.320} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	IguanaTweaksTConstruct{1.7.10-2.0.6} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	AE2 Version: beta rv1-beta-37 for Forge 10.13.0.1187
>	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
>	TConstruct Environment: Environment healthy.
>	SciMCLib Version: 0.0.0.2
>	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, MJ6:OFF, MJ5:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
>	Launched Version: 1.7.10
>	LWJGL: 2.9.1
>	OpenGL: AMD Radeon HD 6900 Series GL version 4.4.13283 Compatibility Profile Context 14.501.1003.0, ATI Technologies Inc.
>	GL Caps: Using GL 1.3 multitexturing.
>Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
>Anisotropic filtering is supported and maximum anisotropy is 16.
>Shaders are available because OpenGL 2.1 is supported.
>
>	Is Modded: Definitely; Client brand changed to 'fml,forge'
>	Type: Client (map_client.txt)
>	Resource Packs: [SFM_retexture.zip, CompyCustom.zip, Norte_Chisel.zip, Invictus-2.1.zip]
>	Current Language: English (US)
>	Profiler Position: N/A (disabled)
>	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
>	Anisotropic Filtering: Off (1)

**Comment by tterrag1098** [comment]
This has been fixed for ages. Please update.

**Comment by MBfromOK** [comment]
Update which mod and to what version?

As far as I can see EnderIO-1.7.10-2.2.6.317 is the newest version and I already have it.

**Comment by Barhandar** [comment]
>EnderIO{1.7.10-2.2.4.309} Ender IO Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available

No you don't. Update.

**Comment by MBfromOK** [comment]
Sorry for the apparent waste of your time, I am not sure what happened, this is a screen capture of my mods folder as of the bug report... As you can see I downloaded EnderIO (from your website) on Jan 3 and it shows the most current filename.

![image](https://cloud.githubusercontent.com/assets/7131008/5693860/8628695c-98f8-11e4-8c0f-2baca2c9cebf.png)

I deleted the original and downloaded the same filename again, the game has been loading  successfully since then.

Thanks for your attention! 

Now I can move on to the original bug I was troubleshooting with EnderIO and OpenBlocks fans.
