### ISSUE TITLE
Round-robin bug

### ISSUE THREAD

**Issue by VictiniX888** [CrazyPants/EnderIO#1625]
When I have an Item Conduit set to round-robin, and I put, say, 8 cobble in there, all 8 cobble go into the same output chest. If I put another 8 cobble in there, they go into the second chest. I'm assuming that 4 cobble would go into each chest if I give the Item Conduit 8 cobble.

Ender IO version 2.2.6.321
Forge version 1284

**Comment by 6210classick** [comment]
if you are using even 1 speed upgrades then it will see 8 cobblestone as a single item because with no upgrades it will extract 4 items at a time so a quick fix is to not use any upgrades it will split evenly however be aware since it extract 4 at a time that means when there is 4 or less it will just shove those in the nearest inventory

**Comment by VictiniX888** [comment]
It happens even without any speed upgrades. If I put 64 cobble in there, all will go into the same chest, instead of 32 each.

**Comment by Lithorn** [comment]
I know this isn't an issue/bug, but could this be suggested into a change for the conduits as such to add a way to control the amount of items sent per extraction? Maybe insted of the conduit extracting X amount of items, it extracts X amount set by the player at + speed based on current speed upgrades. Roundrobin was one of the best things for mass machine automation but ender conduits just can't seem to do it proper for some machines that need a finer selection. TE conduits had this down pact by both being fast, and extraction was set by the player. Speed was based on the conduit used.

To sum it all up, would it be too much to ask of Ender Conduits were altered to allow the player to select the amount of items to extract ranging from 1-64, and use speed upgrades to increase the speed of which the conduit extracts?

**Comment by tterrag1098** [comment]
This can now be solved with the "speed downgrade" item
