### ISSUE TITLE
Server Crash - Me Conduit

### ISSUE THREAD

**Issue by jaxmacky** [CrazyPants/EnderIO#1626]
Server crash while attempting to place an enderio me conduit to an existing item/power enderio bundle, that was attached to a enderio farming station. Could not restart server without a backup. http://pastebin.com/ts6AVQkg

**Comment by jaxmacky** [comment]
Game crash also in single player (testing repeatability) , also resulting in world corruption. Same as above, placing Enderio Me conduit onto a bundle of Enderio power/item conduits. http://pastebin.com/index.php?e=1

**Comment by tterrag1098** [comment]
AE2 rv1 is no longer supported.
