### ISSUE TITLE
Extraction of non-stackable items from Filing Cabinet

### ISSUE THREAD

**Issue by NomAnor** [CrazyPants/EnderIO#1630]
I have a Filing Cabinet from Extra Utilities with a bunch of non-stackable items in it, e.g. Swords.
If I extract the items with an Item Conduit into a normal chest the Conduit puts Stacks of four into the chest instead Stacks of one.

**Comment by 6210classick** [comment]
the item conduit extract 4 items at a time by default with a max of 64 items with 15 speed upgrades

**Comment by NomAnor** [comment]
But if the extracted item has a maximum stack size of 1, so its non-stackable, the conduit should put the 4 extracted items into 4 slots of the chest. Instead it puts stacks of 4 items into the chest which is wrong.

http://imgur.com/OAJUIxO

**Comment by 6210classick** [comment]
wow that's actually a cool bug if you put 15 speed upgrades it will pull a stack of swords and put them in the chest !!

or maybe you are using a mod that allows non-stackable items to stack

**Comment by NomAnor** [comment]
No, its definitely a bug. Tried it with only Ender IO and Extra Utilities:
Forge 10.13.2.1230
EnderIO 2.2.6.317
Extra Utilities 1.2.1

More speed upgrades result in bigger stack sizes.

I think the best fix for this would be to use the minumum of the max stack size of the item being extracted and the extraction stack size given by the upgrades.

How are the speed upgrades effecting the extraction of non-stackable items from normal invenctories? If they only increase the maximum size of the extracted stacks, then speed upgrades have no effect on non-stackable items. Should this be discussed in another issue?

**Comment by tterrag1098** [comment]
Are you saying it dupes the swords? Or just that it pulls 4 at once and then exports them in a single stack?

**Comment by NomAnor** [comment]
No dupe. In the destination inventory you get invalid stack sizes if the max stack size of the extracted item is smaller than the extraction stack size.

**Comment by tterrag1098** [comment]
Ah ok. I see then, thanks.
