### ISSUE TITLE
Bug - Stacked Capacitor Banks w/ Wireless Charger

### ISSUE THREAD

**Issue by Grim-Wolfblood** [CrazyPants/EnderIO#1632]
With a Wireless Charger in operation a newly crafted stack of Capacitor Banks fully charge as one (in inventory of course), costing no more power than it would take to charge a single Capacitor Bank.

**Comment by MatthiasMann** [comment]
Which version do you use? This should have been fixed since version 2.2.0

**Comment by Grim-Wolfblood** [comment]
The FTB modpack I'm using still has 2.1.8. So that's probably it.

I looked over this subsection of the forum and didn't notice any mention of it.

All the same, thank you for the reply.
