### ISSUE TITLE
Bug? - Item Conduits and JABBA Barrels

### ISSUE THREAD

**Issue by Grim-Wolfblood** [CrazyPants/EnderIO#1633]
MFR Farm set up with item conduits and JABBA barrels. Observed conduits starting a new barrel for apples from a vanilla oak tree when an apple barrel already existed, and had plenty of room for additional apples.

Solved by removing apples from new barrel and bumping the insert priority on the old barrel.

Seems to be faulty priority routing that preferred proximity over established storage. If this isn't a bug then consider it a suggestion to give higher priority to existing storage.

**Comment by MatthiasMann** [comment]
Item conduit route in the following way:
1) sticky destinations - priority
2) sticky destinations - proximity
3) priority
4) proximity

The sticky option is only available when you have an item filter in the insertion point. Using this feature you can build what you want.

Destinations which can't accept an item are skipped.

**Comment by iTitus** [comment]
So: This behaviour is intended.
But he requests an option that inventories which already contain the routed items should be prioritized over proximity and inventories on the same priority. That is what AE is doing for Storage Busses.

**Comment by Grim-Wolfblood** [comment]
Your explanation makes sense. However, iTitus is correct. Please consider this a suggestion.

Two purposes barrels serve: 1. Deep storage. 2. Easy item access. I have a single point of contact for an item. I don't have to search an interface.

The conduits, in fact, most things in Ender IO I already consider "best in class", if not in a class all their own. And, with a bit of work I can still make them do everything I currently want.

Not having to do that work because they already make intuitive use my storage... would just be polish on an already great product. If it's not considered for implementation it certainly wont change what I think of the mod.

**Comment by Barhandar** [comment]
Maybe make single-item storage like barrels and DSUs be sticky by default, since it's filtered already on the block's side.

**Comment by tterrag1098** [comment]
The conduits do not care about what is in the inventory, only if the given item can be put in at all. To solve this issue, all you need to do is change the priorities, which it seems you have done.
