### ISSUE TITLE
Map breaking Crash bug

### ISSUE THREAD

**Issue by NJM1564** [CrazyPants/EnderIO#1637]
While trying to apply AE conduit over basic energy conduit the game crashed with the fallowing error. Only removing it using MCeddit could save my world.

http://pastebin.com/7VCbfy56

**Comment by MatthiasMann** [comment]
EnderIO no longer supports AE2-rv1:
https://github.com/CrazyPants/EnderIO/blob/master/ReleaseNotes.txt#L20

You need to update to rv2
