### ISSUE TITLE
EnderIO Redstone & OpenBlocks Fans

### ISSUE THREAD

**Issue by MBfromOK** [CrazyPants/EnderIO#1638]
Minecraft 1.7.10
Forge Mod Loader 7.10.85.1284
Forge 10.13.2.1284
ForgeMultipart-1.7.10-1.1.1.320-universal.jar
EnderIO-1.7.10-2.2.6.317.jar
EnderTech-1.7.10-0.3.0.348.jar
EnderZoo-1.7.10-1.0.5.14.jar
OpenModsLib-1.7.10-0.6-snapshot-225.jar
OpenBlocks-1.7.10-1.3-snapshot-430.jar

I am not sure who I need to report this to and I am not sure how to troubleshoot further so I also posted this in: https://github.com/OpenMods/OpenBlocks/issues/578.

EnderIO Conduits don't seem to interact correctly with OpenBlocks fans, I can place the fan and the conduit, but when I flip the switch and the conduit goes active (brighter red shade) nothing happens.  I have tried every setup I can think of, but no luck.. Screenshot below:

![image](https://cloud.githubusercontent.com/assets/7131008/5693979/1102ec0e-98ff-11e4-9f5a-f261bfe0ef06.png)

These fans don't require power, but can be controlled through a redstone signal.

The only way I have been able to get this to work is with Vanilla Minecraft levers, redstone, and repeaters which add a whole new set of headaches for the mob spawner I built.

Please fix / advise!

Thanks for the help!

**Comment by hilburn** [comment]
This is an OpenBlocks issue:
They make us of world.getStrongestIndirectPower(x,y,z) to calculate the redstone signal strength, which checks adjacent blocks for indirect power. Conduits don't actually supply any redstone signal strength that they are in, just to blocks that they are pointed at.
As far as I can tell the easiest fix on their end would be to check for indirect power in the fan's block, as well as adjacent ones. And I'll note that on the issue you've opened over there
As for you using conduits and fans until it' fixed, try placing a block between them and pointing the conduits into the block with "strong" power selected. Should work ok

**Comment by MBfromOK** [comment]
Thanks for the suggestion, it doesn't work unfortunately, I tried to set one and then both sides to strong power and neither the fan on top or in front of the block will switch.

It was worth a shot!

**Comment by hilburn** [comment]
Out of date openblocks is apparently the issue ^^

**Comment by MBfromOK** [comment]
Thanks for the help and replies, I responded to his message and while I
addressed it to him I expresses some of the angst I began to experience
while trying to fix my game crash in this github regarding versioning and
ease of updating (in that case I was running a file downloaded from one of
the minecraft mod download sites that was named
EnderIO-1.7.10-2.2.6.317.jar and turned out to be EnderIO-1.7.10-2.2.4.309
when you read through the minecraft logs.

Hopefully you will read it as well and pass along anything you deem helpful
to your fellow programmers.. I will update OpenBlocks tomorrow and
hopefully get to see my modspawner in action for the first time!
