### ISSUE TITLE
Soulbound enchant's level values result in 'issues' with other mods

### ISSUE THREAD

**Issue by Barhandar** [CrazyPants/EnderIO#1640]
Enchantment Plus flat-out cannot enchant it, because it sets the bookshelf/level requirement to enchant's "max level", which seems to be 2 billion or so for Soulbound.

Extra Utilities's Magical Wood results in 1 wood across the board, presumably due to min level being low or even 0.

**Comment by 6210classick** [comment]
it's working fine you cannot put Soul-bound using advanced enchantment table there is 2 ways to get it one is 1% of getting it randomly using vanilla enchantment table with 30 levels 

or Book & quill + Ender Crystal with at least 30 levels in Soul Binder or The Enchanter

**Comment by Barhandar** [comment]
My soulbound-enchanted armor disagrees on there being only two ways to get it onto a book.

'Issues' being highlighted in that way is there for a reason, I'll wait for someone more... respectful to punctuation... to say if it's, indeed, intended behavior or not.

**Comment by 6210classick** [comment]
this enchantment is not normally obtainable from enchantment table , proof is to dis-enchant an armor or a tool with Soul-bound and you will get absurd amount of levels

so you have to get the book then combine it with the armor or the tool you desire

**Comment by tterrag1098** [comment]
@6210classick Please check your facts. Soulbound is indeed obtainable from an enchanting table.
