### ISSUE TITLE
Farming station not accepting Project Red Hoes

### ISSUE THREAD

**Issue by Protheus** [CrazyPants/EnderIO#1641]
Using:
- Forge: 1277
- EIO: 321

I have added the project red to teh whitelist of the farming station as:
        ProjRed:Exploration:projectred.exploration.hoeruby
        ProjRed:Exploration:projectred.exploration.hoesapphire
        ProjRed:Exploration:projectred.exploration.hoeperidot

After loading the world they are still not being accepted. I check many times the naming and the naming of the hoe is correct. Any other hoe that I add gets added perfect except the PR hoes.

Any suggestions ?

**Comment by 6210classick** [comment]
EIO : 321 ??? what version is this ?? the latest is 2.2.6

**Comment by MatthiasMann** [comment]
The Project Red hoes should already be in the default config starting with build 318

To restore the default list just delete the S:farmHoes entry from your config file and it will be replaced by the default one.

And the reason why your manually added hoes do not work is a typo (see the | vs : after ProjRed). The right names are:
ProjRed|Exploration:projectred.exploration.hoeruby
ProjRed|Exploration:projectred.exploration.hoesapphire
ProjRed|Exploration:projectred.exploration.hoeperidot

**Comment by Protheus** [comment]
Sorry yes it is 2.2.6.

I have WailaNBT and I used that to check the naming and it showed me a : and not the | - but will try that out and also delete the entries and see if that works. for me this is closed and fixed - thank you

**Comment by Barhandar** [comment]
Minecraft's default font's | has a blank space in the middle, so it's very easy to confuse with :.

**Comment by Protheus** [comment]
fixed
