### ISSUE TITLE
Updated to 322 Conduit issue 

### ISSUE THREAD

**Issue by BuckitHead** [CrazyPants/EnderIO#1642]
I updated to 322 and we started having render issues on conduit. Went back to 321 and they are still there. Server is spaming the console with:
11.01 11:15:14 [Multicraft] Skipped 88 lines due to rate limit (30/s)
11.01 11:15:06 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:50)
11.01 11:15:06 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:50)
11.01 11:15:06 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:50)
11.01 11:15:06 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:50)
11.01 11:15:06 [Server] Server thread/INFO [STDERR]:

**Comment by BuckitHead** [comment]
rolled the world back to last nights save and config file and everything is good again. This was a weard issue. it was causing everything around the conduits to render bad after about 2 min and not just ender Io items. there was issues with redstone furnice render as well. This was only affecting newly placed conduit.

**Comment by BuckitHead** [comment]
Spoke to soon.... Rolling back to forge 1277 from 1284 to see if that fixes, will let ya know

**Comment by BuckitHead** [comment]
ok so seems to be issue with forge 1284. not sure what but something for you know going forward

**Comment by tterrag1098** [comment]
You need to get the full log.

>11.01 11:15:14 [Multicraft] Skipped 88 lines due to rate limit (30/s)

I need those 88 lines as they have the actual stack trace.

**Comment by BuckitHead** [comment]
http://www.mediafire.com/download/1l1boqzhlqnthid/fml-server-latest.log

If you need anything else let me know

**Comment by BuckitHead** [comment]
First off I want to apologize for a issue on my end. seems that a chunlk loader was removed causing this area to unload and the server to throw issues to log. Took me some time but all is good now after about an hour. again sorry for wasting any of your time.
