### ISSUE TITLE
Feature request: Walia support for Fluid conduit

### ISSUE THREAD

**Issue by Slychocobo** [CrazyPants/EnderIO#1651]
It can be somewhat confusing doing pipework as there does not appear to be a way to tell what fluids are currently in a conduit.

Walia support (or a in-game item, such as the conduit probe) would be quite useful.

**Comment by 6210classick** [comment]
use Yeta wrench if you press Y it will show only the conduit type you want to see

**Comment by tterrag1098** [comment]
Complete as of @MatthiasMann's PR
