### ISSUE TITLE
Localize keybinds/Waila

### ISSUE THREAD

**Issue by Adaptivity** [CrazyPants/EnderIO#1652]
1) http://i.imgur.com/ZGzzmc7.jpg
2) http://i.imgur.com/FmTyugL.jpg
Code location: https://github.com/CrazyPants/EnderIO/blob/9676e8291ebb338dc9448df3aca5f7a6939a6aa5/src/main/java/crazypants/enderio/item/KeyTracker.java#L58-L74
3)Waila https://github.com/CrazyPants/EnderIO/blob/ff4ef4ffd33838f9c03ec43eafd3473d59d33031/src/main/java/crazypants/enderio/waila/WailaCompat.java#L63
4) TooltipAddera.java "burn time"

**Comment by tterrag1098** [comment]
Can the WAILA stuff easily be localized? I wasn't sure if I could pass in unlocalized names for that.

**Comment by Adaptivity** [comment]
Can be. https://github.com/SlimeKnights/TinkersConstruct/commit/6b4e72e189c72e0e837bae2656e32df89333836c You should just delete "Sneaky Facades" add it into .lang file. How to localize keybinds I don't know.

**Comment by tterrag1098** [comment]
KeyBindings work the same as that I believe

**Comment by Adaptivity** [comment]
You should do it better than I'm since I'm just translator and not a coder.
