### ISSUE TITLE
texture bug on soul binder

### ISSUE THREAD

**Issue by Deckee** [CrazyPants/EnderIO#1657]
1.7.10 Forge 1277 
Soul binder using texture from ender infused obsidian and chisel marble
not game breaking but anoying

![2015-01-12_22 03 50](https://cloud.githubusercontent.com/assets/8199121/5715928/f37a259e-9aa7-11e4-80e6-b828e3fcfdca.png)

**Comment by tterrag1098** [comment]
Fixed
