### ISSUE TITLE
ME conduits infinate replication on the network

### ISSUE THREAD

**Issue by kurokuno** [CrazyPants/EnderIO#1660]
if some ME conduits become unloaded they create more conduits where the connection is cut off "no i dont mean this in the sense that they drop or duplicate conduits" i mean my network sees more and more conduits that are not there last night it got to over 9700 ME conduits  and was using a constant 2k power because of this bug now i know this is more a chunk loading issue but i was woundering if there was maybe someway to safeguard against this happening for now i have just made sure all of my base is loaded at all times!!

**Comment by TheJulianJES** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/725

**Comment by tterrag1098** [comment]
Duplicate #1518
