### ISSUE TITLE
Bedrock Hoe in farming station

### ISSUE THREAD

**Issue by MinoCraft** [CrazyPants/EnderIO#1661]
Hello,

I use the last Ender IO version and I can't put RotaryCraft Bedrochk hoe inside the farming station.
I have an hold farming station and I have a bedrock hoe inside as you can see in the picture:
https://imgur.com/a/96b1c

Thanks in advance !

**Comment by tterrag1098** [comment]
You must whitelist it in the config.

**Comment by MinoCraft** [comment]
Ok thank you very much !
I had not seen the whitelist in the config file :/
