### ISSUE TITLE
ME conduit does not correctly connect to AE2 terminals

### ISSUE THREAD

**Issue by kayila** [CrazyPants/EnderIO#1670]
From talking with the AE2 people, they said EnderIO needs to support adding AE 'parts' in order to work with the new terminals.

**Comment by 6210classick** [comment]
yeah it has no support for it at the moment and they are supper buggy also you can connect a normal me cable with terminals then hook it up to the conduit

**Comment by 4rz0** [comment]
Having the same issue.
Atm I prefer the AE2 cables because of that issue.

**Comment by tterrag1098** [comment]
It's not easy (and perhaps not possible) to support AE parts on ME conduits. I may pursue it in the future but for now it will remain as it is.
