### ISSUE TITLE
Dark Steel Ball Bug

### ISSUE THREAD

**Issue by MinoCraft** [CrazyPants/EnderIO#1673]
Hello,

I use the last version of Ender IO and when I put dark steel ball in SAG Mil the percentage arrives in denial before passing in the following ball. The following ball is used when the percentage is at -300%
I'm not sure if this is a problem !  
You can see the problem in this picture: http://i.imgur.com/WHbL4VL.png

Thanks in advance !

**Comment by 6210classick** [comment]
working fine for me it's shows 100% using the exact same configuration as yours

with the latest EIO 2.2.6 317 and the latest FORGE 1286

**Comment by MatthiasMann** [comment]
That issue was not easy to reproduce - but it happened to me too.
