### ISSUE TITLE
Advanced Photovoltaic cells bug.

### ISSUE THREAD

**Issue by noblehallett** [CrazyPants/EnderIO#1676]
Using the Direwolf20 1.7.10 feed the beast pack server these cells caused 5 Mbps upload for a single user client connected over the internet. We had 5 stacks of the cells in use.

**Comment by tterrag1098** [comment]
Update your pack.

**Comment by tterrag1098** [comment]
And PLEASE report modpack bugs to the modpack AUTHOR. They are almost always on an OLD version.
