### ISSUE TITLE
Crash with ME conduit

### ISSUE THREAD

**Issue by Shuudoushi** [CrazyPants/EnderIO#1680]
There seems to be a nasty crash when placing ME conduits on ender energy conduits <s>that are ran by/near AE2 glass cables.</s> Upon more testing, it seems that placing ME conduits on ender energy conduits at all causes the crash, with or without the AE2 cable in place.

Crash one (upon placing the conduit): http://pastebin.com/S6GG1XqE

Crash two (upon trying to reload the world to take screenshots of the setup): http://pastebin.com/3d5QakyJ

Screenshot of the setup: 
![highlight_crash](https://cloud.githubusercontent.com/assets/4585237/5756468/86bf5404-9c75-11e4-8452-920ca1e070c4.png)

**Comment by Adaptivity** [comment]
God, why.. https://github.com/CrazyPants/EnderIO/issues/1626 rv1 NO LONGER supported.

**Comment by Shuudoushi** [comment]
I knew I should have looked at the logs more in-depth... I'll tell the server admin to update AE2...
