### ISSUE TITLE
Travel anchor does not seem to respect config's range setting

### ISSUE THREAD

**Issue by Villermen** [CrazyPants/EnderIO#1684]
This is from my experience in direwolf20 (1.0.3). The range config option (travelAnchorMaxDistance in EnderIO.cfg) doesn't seem to change anything. After changing it to -1, 0, 2000 and 200 the max distance stayed at it's default (of 48?). Travel anchors won't pop up at longer ranges. Also, the config option seems to appear twice (in "settings" and in "anchor settings"). I have changed both of them to the same test value and then restarted the server each time.

Gr.Viller

**Comment by MatthiasMann** [comment]
The range is limited by the viewing distance and the also by the travelStaffMaxDistance.

**Comment by Villermen** [comment]
Viewing distance means the chunk has to be loaded in memory right? Because I'm pretty sure that's further than exactly 48 blocks. With the staff (that I just made) the max distance is the default 96, which is more than anchor-to-anchor allows (even though that is set to 2000 right now).

**Comment by 6210classick** [comment]
try putting a chunk loader one in the first travel anchor and second in the other travel anchor

**Comment by Villermen** [comment]
The chunk loader thing didn't do it, but changing the staff's range did strangely enough.

**Comment by tterrag1098** [comment]
If you are using the staff to teleport between anchors that config is used. Otherwise, if you are travelling from block to block (i.e. jumping), it will use the config you mentioned.

**Comment by Villermen** [comment]
Well yeah, but still there does seem to be a lot of weird rules that I don't quite get. For example, why can I see a travel anchor when my friend cannot? We both have the same render distance.
