### ISSUE TITLE
RF API Intolerance

### ISSUE THREAD

**Issue by joflashstudios** [CrazyPants/EnderIO#1696]
EnderIO's finicky RF API behavior is making my life as a server admin very difficult. Instead of machines simply not working or conduit not transferring power when there are issues, EnderIO seems to crash the entire game/server every time anyone sneezes. I've had to manually fix things in MCEdit, remove and re-add the mod entirely, and jump through numerous hoops just to get our world usable. Is there any way EnderIO could just not work, instead of crashing everything? I believe it is related to this: https://github.com/erogenousbeef/BigReactors/issues/404#issuecomment-67992285

I can supply error logs if you want, but they come from things as varied as MFR energy systems to BigReactors systems. Whenever anything touches EnderIO, you have to hold your breath and hope it doesn't make your world unusable. Before you ask, yes, everything is up-to-date.

**Comment by 6210classick** [comment]
then just use older version of EIO most mods aren't updated with the latest RF API

**Comment by tterrag1098** [comment]
What? How is it our fault one of your mods has an old API. No there isn't a way it could just "not work". Blame CoFH for your problem, not us.
