### ISSUE TITLE
Fluid duplication bug via Fluid Tanks + Buckets

### ISSUE THREAD

**Issue by Slychocobo** [CrazyPants/EnderIO#1701]
In version 2.2.6.317 it is possible to duplicate fluids using a Fluid tank.

[REDACTED]

**Comment by 6210classick** [comment]
i can't seem to do that using both the normal tank and the pressurized with same version with forge 1286 however i found something interesting if you set it to push on any side you cannot use bucket on that tank to fill it and vice-verse and if you set it to disable you no longer can fill it up or take liquids from it i don't know if this is a bug or intended but it's kinda cool

**Comment by tterrag1098** [comment]
Fixed in @MatthiasMann's PR. Sensitive info redacted.
