### ISSUE TITLE
[Request] Add "Silky Lining" to Dark Steel Armour :)

### ISSUE THREAD

**Issue by Karmacopper** [CrazyPants/EnderIO#1703]
Please add the ability to enhance DSA with Forestry Apiarists armour pieces to add a lining to the DSA with the same properties of the apiarists armour. ie negate bee effects.

**Comment by 6210classick** [comment]
do you mean as an enactment ? or as power-up for the DS armor ?

**Comment by Karmacopper** [comment]
I'd say as a power up as I don't take your meaning on "enactment".

Add via the anvil eg apiarists pants to DSA leggings etc

**Comment by 6210classick** [comment]
** enchantment , my bad

**Comment by tterrag1098** [comment]
Implemented in above commit
