### ISSUE TITLE
Powered Spawners & Wither Skeletons

### ISSUE THREAD

**Issue by Karmacopper** [CrazyPants/EnderIO#1707]
Using latest DEV build (323)

Build new powered spawner, captured Wither Skeleton, bound it to a broken spawner (Silver Fish) Set it running in the Overworld in my spawning enclosure. It only produces white skeletons.

Mod List:
Name

1.7.10
carpentersblocks
railcraft
[1.7.10]Treecapitator-universal-2.0.4.jar
AOBD-2.3.5.jar
appliedenergistics2-rv2-beta-7.jar
BattleText-1.7.10-r1.jar
bdlib-mc1710-1.5.1.32.jar
BiblioCraft[v1.9.1][MC1.7.10].jar
BiblioWoods[BiomesOPlenty][v1.9].jar
BiblioWoods[Forestry][v1.7].jar
BiblioWoods[Natura][v1.5].jar
BigReactors-0.4.0A.jar
binnie-mods-2.0-pre3.jar
BiomesOPlenty-1.7.10-2.1.0.1019-universal.jar
buildcraft-6.2.2.jar
Carpenter's Blocks v3.3.4 - MC 1.7.10.jar
ChickenChunks-1.7.10-1.3.4.14-universal.jar
Chisel-1.7.10-1.5.7.jar
CodeChickenCore-1.7.10-1.0.4.29-universal.jar
CoFHCore-[1.7.10]3.0.0B8-36.jar
denseores-1.5.jar
endercompass-1.7.10-1.0.jar
EnderIO-1.7.10-2.2.6.323.jar
EnderStorage-1.7.10-1.4.5.26-universal.jar
EnderZoo-1.7.10-1.0.9.18.jar
ExtraTiC-1.7.10-1.0.3.jar.disabled
extrautilities-1.2.0.jar
FastLeafDecay-1.7.10-1.0.jar.disabled
Flesh2Lether [1.7.10b].jar
forestry_1.7.10-3.3.0.6.jar
gendustry-mc1710-1.4.3.47.jar
industrialcraft-2-2.2.656-experimental-api.jar
InventoryTweaks-1.58-147.jar
ironchest-1.7.10-6.0.51.734-universal.jar
Jabba-1.1.4_1.7.10(1).jar
JourneyMap5.0.1_Unlimited_MC1.7.10.jar
logisticspipes-0.8.2.83.jar
Mantle-1.7.10-0.3.2.jar
Mekanism-1.7.10-7.1.1.127.jar
MekanismGenerators-1.7.10-7.1.1.127.jar
MekanismTools-1.7.10-7.1.1.127.jar
Metallurgy-1.7.10-4.0.6.80.jar
MetallurgyCore-1.7.10-4.0.4.18.jar
MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar
MmmMmmMmmMmm-1.6.jar
ModularPots-1.7.10.14.jar
MrCrayfishFurnitureModv3.4.7(1.7.10).jar
natura-1.7.10-2.2.0.1.jar
neiaddons-mc1710-1.12.3.11.jar
NEIIntegration-MC1.7.10-1.0.3(1).jar
NetherOres-[1.7.10]2.3.0RC3-84(1).jar
NoMoreRecipeConflict-0.2(1.7.10).jar
NotEnoughCodecs-1.7.10-0.3-snapshot-11.jar
NotEnoughItems-1.7.10-1.0.3.73-universal.jar
OpenBlocks-1.7.10-1.3-snapshot-513.jar
OpenModsLib-1.7.10-0.6-snapshot-268.jar
Railcraft_1.7.10-9.4.0.0.jar
RedstoneArsenal-[1.7.10]1.1.0RC1-19.jar
ShowDurability2-1.7.10-1.4.0.jar
SimplyJetpacks-MC1.7.10-1.3.1.jar
StevesCarts2.0.0.b18.jar
TConstruct-1.7.10-1.8.0.jar.disabled
TConstruct-1.7.10-1.8.1.jar.disabled
ThermalExpansion-[1.7.10]4.0.0B6-16.jar
ThermalFoundation-[1.7.10]1.0.0B3-8(1).jar
TiCTooltips-mc1.7.10-1.1.11b.jar.disabled
Waila-1.5.5_1.7.10.jar
WailaHarvestability-mc1.7.x-1.1.0.jar
Wawla-1.0.9_1.7.10.jar

**Comment by mattymaats** [comment]
Put it in the nether, it'll work then..

**Comment by 6210classick** [comment]
don't ask why its a vanilla thing if you need more wither spawners just catch a normal skelton

**Comment by tterrag1098** [comment]
Guys, if you can't solve the problem, you aren't helping. He is
troubleshooting a new feature that FIXES the behavior you are talking
about.

**Comment by mattymaats** [comment]
If you are planning on adding this in please can you put in the availability to disable it? 

This bug will be the same reason the MFR auto spawner has the option to spawn exact copy, even if you capture a wither skeleton inside a safari net and try to auto spawn it it will produce skeletons unless you set it to exact copy.

**Comment by tterrag1098** [comment]
It has been added and there is a config to turn it off

**Comment by Staegrin** [comment]
Using version EnderIO-1.7.10-2.2.7.325
![2015-01-29_03 41 18](https://cloud.githubusercontent.com/assets/8494635/5951577/91c22f30-a769-11e4-844b-25e6eebf6a52.png)
Quarrying the nether. Hordes of skeletons keep spawing in the same X a

**Comment by tterrag1098** [comment]
This has been fixed in the latest builds. To be released soon.

**Comment by Staegrin** [comment]
Thanks. Wasn't sure if I should report it or not after going through the open issues.

**Comment by tomasdev** [comment]
What was fixed? The last comment or the original issue about being unable to spawn Wither Skeletons in the overworld?

**Comment by HenryLoenwind** [comment]
That was 2 years ago...
