### ISSUE TITLE
Abundant broken spawners

### ISSUE THREAD

**Issue by joshbogs** [CrazyPants/EnderIO#1708]
Hello,
 So I have been playing a SSP map with this mod as well as RotartyCraft. I have been experiencing a 100% drop rate of broken spawners while using both the HLSA steel and bedrock pics. Both un-enchanted. Just wanted to share since I know they are chance based.

**Comment by tterrag1098** [comment]
No they aren't...? Broken spawners drop 100% of the time.

**Comment by joshbogs** [comment]
Thanks. Made me check through the configs and found its an option. Ends up its a config setting. Looks like my last pack had it less the 1 chance which made me think otherwise.
