### ISSUE TITLE
Placing ME conduit next to AE2 P2P tunnel corrupts chunk

### ISSUE THREAD

**Issue by asdaa0** [CrazyPants/EnderIO#1720]
I was playing on a server and my friend decided to to use ME conduits for P2P tunnels to hide them with covers. While he was working on that he placed an ME conduit next to the P2P tunnel then the server crashed and corrupted the chunk that we were in. 

Reproduced in SP:  http://pastebin.com/bvuFmDvW

Modpack: DNS Techpack 7.5.4.4
EnderIO version: 1.7.10 2.2.6.322

**Comment by tterrag1098** [comment]
rv1 is no longer supported.
