### ISSUE TITLE
Item Conduits don't connect to TE Machines

### ISSUE THREAD

**Issue by OldOpa** [CrazyPants/EnderIO#1722]
The Item Conduits don't connect to TE Machines. 

I'm using the latest EnderIO version (EnderIO-1.7.10-2.2.7.325) and the latest TE (ThermalExpansion-[1.7.10]4.0.0B8-23)

Item Conduit (is NOT disabled):

![2015-01-20_19 31 54](https://cloud.githubusercontent.com/assets/10256143/5823355/46bfb220-a0dc-11e4-9d11-c7122d25ec4b.png)

GUI showing only Energy Conduit:

![2015-01-20_19 32 31](https://cloud.githubusercontent.com/assets/10256143/5823365/5fd88c1e-a0dc-11e4-9517-07d2cef0dc4c.png)

**Comment by mattymaats** [comment]
Have you tried picking up the machine and placing it back down? I've noticed if you put the pipe down after it doesn't actually update the connection so placing the TE machine back down seems to link it back up for me.

**Comment by OldOpa** [comment]
I tried, also I broke the Item Conduit and placed it again. Also I tried to place only a Item Conduit without the Energy Conduit, still no connection. After some testing it worked again. Don't know why it didn't work for me in the first time.

Thanks for your time and help!
