### ISSUE TITLE
Capacitor Banks timings

### ISSUE THREAD

**Issue by kevinkk525** [CrazyPants/EnderIO#1728]
Don't get me wrong, the EnderIO Capacitor Banks are the best energy storage systems I have ever seen! 
They need 1/5 of the timings of a MFSU from IC2 and 1/3 of Resonant Energy Cell from TE and in huge amounts as a battery even better than that.

But is there a way of even lowering the timings for Capacitor Banks as a Multiblock?
On my server one Vibrant Capacitor Bank needs 0.854µs and therefore my huge battery with 8000 blocks takes 6.8ms which does impact the server tick time quite noticeable.

So is there some potential solution to even optimize these blocks a little more, especially as multiblock-structure?
(Or is there a way of limiting the amount of Capacitors one player can place? - Did not find a mod for that)

**Comment by kevinkk525** [comment]
After using a different server the timings went down to 0.09µs, so the 8000 block multiblock takes only 710µs which is more than good enough actually. The difference to the other energy mods is even bigger now. 
So please change this into a huge "Thank you!" thread. Really good work!

**Comment by tterrag1098** [comment]
Version? Other mods? Which dimensions?
