### ISSUE TITLE
[Bug?]Conduit facades painted with Binnies Mod woodworked block

### ISSUE THREAD

**Issue by Karmacopper** [CrazyPants/EnderIO#1732]
I thought I'd try painting a conduit facade with the product of Binnies Mod woodworker and upon placing the conduit facade into the world CTD'd with the following log...

Appears I'll have to world edit the facade out too.

http://paste.ee/p/eRTi2

**Comment by tterrag1098** [comment]
This should be fixed now, it won't crash, but that doesn't mean the facade will render properly. Some things just won't work.
