### ISSUE TITLE
AE conduits still available

### ISSUE THREAD

**Issue by tannerah** [CrazyPants/EnderIO#1739]
players that don't know that AE support has been removed place the cables and corrupt worlds, can we please remove these.

**Comment by tterrag1098** [comment]
You misunderstand. We no longer support rv1 of AE2. Newer versions work fine.

**Comment by tannerah** [comment]
OK then the mod pack guys aren't updating in line




Sent via the Samsung Galaxy Tab® S, an AT&T 4G LTE tablet


-------- Original message --------
