### ISSUE TITLE
Killer Joe attacks the air

### ISSUE THREAD

**Issue by unpure** [CrazyPants/EnderIO#1742]
Hey there.
Currently working on a nice mob farm for my base.
I want to use Killer Joe and everything is working fine.
For some reason Killer Joe seems to always attack twice.
Its ok for mobs that need more then 1 hit.
But its useless for chickens or even for all other mobs if the sword is strong enough.
So with a tank (16 buckets) of nutrient distillation i could kill 3200 chickens.
But because of that double attack only 1600.
Not that important but i think its a bug.

Sorry for my bad english, i hope its not to hard to understand.

**Comment by tterrag1098** [comment]
Thanks, fixed
