### ISSUE TITLE
Suggestion - RoundRobin - Machine Upgrades

### ISSUE THREAD

**Issue by Lithorn** [CrazyPants/EnderIO#1747]
Roundrobin was nice with TE Conduits as it had a fine tuning method to extraction. Ender Conduits do somewhat the same thing but they don't seem to work so nice with certain machines like the Alloy Smelters. The extraction often pulls too many even with no upgrades and leaves machines stuck with resources it can't complete with. 

Machines are slow, and the ability to add upgrades helps quite a bit. Despite this, machines are still a bit slow. If RoundRobin was working properly this wouldn't be an issue as you could just make a few more in the line to handle the excess. 

My suggestion is this: Give Item conduits the ability to choose the amount to extract but make the speed upgrades alter the extraction pace instead of amount.

 (TE Conduits I think pulsed at 1s for normal, and .5s for the improved one. 1 speed upgrade could cut the extraction time in half for that same pulse speed, thus only needing 1 upgrade instead of 15. This basically means it becomes just like the TE item conduit so I don't know how you will feel about this. TE still hasn't released their new conduits so I am seeking other options. ) Maybe you could make a special upgrade that adds this functionality in? 

It would be nice if the machine upgrades from Capacitors could stack or was just a bit faster but that is a personal preference.

**Comment by 6210classick** [comment]
or maybe separate the item conduits to 2 types one transfer 1 item at a time and the second does the same as the current item conduits 4 at a time

the first one will need a 63 speed upgrades to pull a stack

Round Robin  work perfectly however it needs to be at least 4 items if less it will just send it to the nearest machine , why not create an EIO factory like a 16 alloy smelter 8 for the energetic alloy and the other 8 for vibrating alloy

if you are using AE to automate your machines then use an item buffer or a chest that alloys goes to it then get extracted to machines with item conduits and filter then importing it back to the system

**Comment by tterrag1098** [comment]
A "speed downgrade" has now been implemented which will allow 1 item to be transferred per operation.

**Comment by Lithorn** [comment]
The issue is, it pulls 4 at a minimum speed, if there is less than 4 coming in then it will just send whatever into the line. This leads to machines getting jammed by having more or less of the even amount of items per machine. 

Speed downgrade sounds awesome, but in the future, will there be a way to increase that extraction speed? Maybe have the item conduit transfer 1 at a time but at 1/4th the speed of what it would be to send 4 at a time?  So like 1S to send 4 items would be .25S to send 1?  Or maybe just cut the extraction speed to half a second for single extractions?
