### ISSUE TITLE
[Suggestion] Replaceable Spawner

### ISSUE THREAD

**Issue by accessdenied0** [CrazyPants/EnderIO#1753]
Hi CrazyPants,

I don't know if this suggestion is already made... I risk it anyway:

can you implement a possibility or a config option to make it possible to place a Broken Spawner down again?

Maybe with Silktouch broken ones? , In cost of a Emerald and a Spawner in an Anvil? Or in cost of 30 XP?

I know this is a bit OP, but I would like this feature.

Thank you for reading and maybe adopting,

access_denied

**Comment by MatthiasMann** [comment]
The broken spawners can be bound to a powered spawner in an anvil which can then be placed.
There are many other mods provide ways to move vanilla spawners without breaking them.

**Comment by accessdenied0** [comment]
Sure thing man, 

but already broken, there are useless for other possibilities... so I ask me, why instead of complicated... not easy? It would be a nice "thing-to-have" if there would be such a method to convert or place them again... and/or "maybe" I don't want other mods... But it was just an idea.

I will wait,

access_denied

**Comment by 6210classick** [comment]
it's not necessary CrazyPants and his team did a really good job balancing EIO in my opinion the spawners are perfectly balanced they work exactly as the vanilla ones except they need power a lot of power a big reactor level for some of the mobs specially after the latest update Wither Skeletons are now a separate entity no other mob spawner mods had ever attempt this

also did you know that you can just combine a broken spawner with any powered spawner even if the mob type was already set , you can also use the Soul Binder to change any broken spawner type to any other mob even non-vanilla ones the exception is iron golem & villagers

you shouldn't request a Replaceable Spawners instead request a tool that consume a lot of RF that is capable of moving any block much like Matter Transporter from Practicalities Mod

**Comment by accessdenied0** [comment]
Hi 6210classick,

that would be an option, too. I'm aware of the efforts which are made to balance this mod and I don't want to change that. I thought it might be easy to just add a option or a possibility to convert/replace the spawner to use them for other purposes. I mean: Anything else can be modified... from energy consume until recipes outputs.

Can you follow my thoughts?

I hope the best,

access_denied

**Comment by tterrag1098** [comment]
I don't think this will be implemented. If you want the spawner to stay in block form, you should not mine it (or find another way to move it)

**Comment by accessdenied0** [comment]
Sadness... from both programmer and mod...
It would be a great addition possibility... 
but well. Thank you anyway.
