### ISSUE TITLE
ME conduits consistently fail to correctly connect/transport

### ISSUE THREAD

**Issue by SubsterNL** [CrazyPants/EnderIO#1755]
ME conduits (both dense and normal) consistently fail to be usable. They show weird connector textures and fail to be reliable or usable. Usaly they pop off the existing AE2 machine/cable when trying to connect to it.

Version EnderIO-1.7.10-2.2.7.329 (but has been happening since many version before)

**Comment by tterrag1098** [comment]
This has been reported quite a few times and I am aware of the issue
