### ISSUE TITLE
Vibrant Capacitor Bank Bug 

### ISSUE THREAD

**Issue by arman258** [CrazyPants/EnderIO#1758]
I'm am experiencing the same bug as #1445 in the latest version of EnderIO in a modpack called SkyFactory version 2.2.3. 
The Capacitor won't allow me to set input mode in the side where the tesseract is attached to.

**Comment by MatthiasMann** [comment]
The tesseract signals that is only accepts power and does not output power - that is why the cap bank won't offer input mode.
