### ISSUE TITLE
Excessive skeleton spawning in the Nether

### ISSUE THREAD

**Issue by MrKunji** [CrazyPants/EnderIO#1761]
There are tons of 'Wither Skeletons' spawning in fortresses, but they are just common overworld skeletons with a hell of speed that don't inflict Wither effect:
http://imgur.com/a/cguMt
Mod list atached in the album
This happened in two modpacks (with same EnderIO version), but in the second, I saw a 'totem' of skeletons and the client stopped.

**Comment by tterrag1098** [comment]
What version of EIO? What other mods are installed?

**Comment by MrKunji** [comment]
I said, mod list in the album, all files have the mod version.

**Comment by Dragunkod** [comment]
go into the config and find this
"replacewitherskeletons {
    # Separates wither and normal skeletons into different entities, enables the powered spawner to treat them differently [EXPERIMENTAL - MAY CAUSE ISSUES WITH OTHER MODS]
    B:Misc=true"
and change it to false.
it will fix the problem.

**Comment by MrKunji** [comment]
I knew it was related to that change. Gonna try it tomorrow :)

**Comment by tterrag1098** [comment]
This is still a bug....

**Comment by OronDF343** [comment]
Still happens in latest commit.
