### ISSUE TITLE
Wireless charger doesn't charge Dark Steel Axe in Farming Station

### ISSUE THREAD

**Issue by og1996** [CrazyPants/EnderIO#1763]
With a fully-upgraded Dark Steel Axe (Empowered IV enchanted with Unbreaking III), placed inside the farming station, it will not receive a charge from the wireless charger. This works with the Ender in a Killer Joe, so it would be nice to be consistent.

**Comment by tterrag1098** [comment]
That's a rabbit hole I don't think I want to go down. Where does it end? Should the wireless charger support ALL inventories? The Killer Joe makes sense to me because it is like a player, it holds the sword out in the open for charging. A farm is just another block with an inventory.
