### ISSUE TITLE
CrazyPants ElectricLight crashing FTB DireWolf 1.0.2 and 1.0.3

### ISSUE THREAD

**Issue by ZizzyZizzy** [CrazyPants/EnderIO#1766]
Unable to get anywhere near the block without the server crashing and restarting. (1.0.2 was Forge only, 1.0.3 is running MCPC+)

Short crash report:
-- Block entity being ticked --
Details:
    Name: blockElectricLightTileEntity // crazypants.enderio.machine.light.TileElectricLight
    Block type: ID #1164 (tile.blockElectricLight // crazypants.enderio.machine.light.BlockElectricLight)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-809,88,-453), Chunk: (at 7,5,11 in -51,-29; contains blocks -816,0,-464 to -801,255,-449), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
    Actual block type: ID #1164 (tile.blockElectricLight // crazypants.enderio.machine.light.BlockElectricLight)
    Actual block data value: 0 / 0x0 / 0b0000

Long report:
http://pastebin.com/V6KDDqae

**Comment by tterrag1098** [comment]
The crash you have posted has nothing to do with EIO

**Comment by ZizzyZizzy** [comment]
Could you elaborate? The ticking tile entity report was very specific about the block causing the crash.
 Actual block type: ID #1164 (tile.blockElectricLight // crazypants.enderio.machine.light.BlockElectricLight)

**Comment by ZizzyZizzy** [comment]
OK, this is interesting. The fml log shows a different error than the crash report .txt file:

[19:36:16] [Server thread/ERROR] [FML/]: A TileEntity type vswe.stevescarts.TileEntities.TileEntityDistributor has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class vswe.stevescarts.TileEntities.TileEntityDistributor is missing a mapping! This is a bug!

**Comment by ZizzyZizzy** [comment]
Comfirmed. Disabling Steve's Carts 2 has allowed me back in the server.

Now I have trust issues with crash reports.
