### ISSUE TITLE
Can't set permissions for Killer Joe fakeplayer

### ISSUE THREAD

**Issue by StarkRG** [CrazyPants/EnderIO#1771]
Apparently ForgeEssentials requires a UUID (despite requiring usernames to add the user to the permissions lists), therefore fakeplayers' UUIDs need to be added manually. Unfortunately I can't figure out what the UUID for the KillerJoe fake player is.

**Comment by Maxiebyte** [comment]
I think that it is c1ddfd7f-120a-4437-8b64-38660d3ec62d. (see <https://github.com/CrazyPants/EnderIO/blob/471f6653514270ebbc02a334b19b68e67c54b690/src/main/java/crazypants/enderio/machine/farm/FakeFarmPlayer.java#L23>)

**Comment by StarkRG** [comment]
Already tried that. In addition it appears that each and every one of the Killer Joes is a separate fakeplayer, suggesting we'd have to add them manually, one by one, into the permissions system.

So I guess what this means is that the Killer Joe is unusable on public servers?

**Comment by tterrag1098** [comment]
The killer joe has a random UUID set by the game. Perhaps suggest to the FE guys to add a class based blacklist as well? Not much I can do here.

**Comment by StarkRG** [comment]
I'm sure there IS something that could be done. MFR grinders, for example, work just fine and don't require new fakeplayers for each and every placed block.

**Comment by luacs1998** [comment]
Hi, I'm a developer of FE.

A possible workaround for this would be to manually add the fakeplayer to the Operators group using the FE API, for now. This would likely have to be done on EnderIO's part, and would introduce a new dependency on FE, which I'm not sure if you're willing to do.

**Comment by tterrag1098** [comment]
Fixed in above commit.
