### ISSUE TITLE
EnderIO + Optifine crash (probably)

### ISSUE THREAD

**Issue by CZDanol** [CrazyPants/EnderIO#1774]
Hey guys,

I suddenly started having this crash:
http://paste.ee/p/nsBBs

It happens after a few minutes of playing, without no obvious reason. Removing either OptiFine or EnderIO stops crashing minecraft. Started experiencing it after placing first item conduits into the world (they were connected to reinforced chests from betterStorage)

Thanks

**Comment by tterrag1098** [comment]
We don't support optifine. Make sure you are using one of the versions that is explicitly labeled for forge support. Most OF versions will not work with most mods.
