### ISSUE TITLE
Ability to color ME Conduit like AE2 Cables

### ISSUE THREAD

**Issue by drewhoener** [CrazyPants/EnderIO#1777]
AE2 cables can be colored so that different types of cable will not interact. What if the ME conduits could have a color system similar to what the redstone conduit has now? That way you can still have one cable, but different outputs based on the color.

**Comment by MatthiasMann** [comment]
You don't need to color them - once the current issues are fixed you can just connect and disconnect them with a wrench like any other EnderIO conduit.

**Comment by drewhoener** [comment]
That's not what I really mean. For example, you have yellow, blue and green cables all connecting to one me conduit, but on different color channels, because they're on different subnetworks. Instead of having to have 3 different me conduits, you could just have one, but with different colors to specify which one it's outputting. Much like how you can have many different redstone signals through insulated redstone conduit by using the color system.

**Comment by MatthiasMann** [comment]
You could always use dense ME conduits to get 32 channels. Even if the AE2 API would allow for such things (which I don't think it does) - it would devalue the dense cables or the P2P tunnels.

**Comment by tterrag1098** [comment]
That would be overpowered compared to regular ME cables, as they can only usually carry one color full of channels.
