### ISSUE TITLE
Item conduits no longer connect to TE tesseracts

### ISSUE THREAD

**Issue by Nentify** [CrazyPants/EnderIO#1778]
![](http://i.nentify.me/gLQDzM08.png)

The item conduits no longer connect to TE tesseracts after updating to 2.2.7 from 2.2.6.

**Comment by nexx** [comment]
I was just coming on here to report this, we noticed it when upgrading to 2.2.7 as well.

It's the same as #1348, and I imagine this issue is down to commit e3e707bd0a8ecf15baa171f7d8c24372dbec96d4

**Comment by MatthiasMann** [comment]
Sounds like the Tesseract returns the wrong value for the canConnectInventory call?

**Comment by stickhead** [comment]
I believe that 4.0.0B8-23 of Thermal Expansion fixes that, just going off of what the guys in TE chat told me

**Comment by Nentify** [comment]
I'm using B8-23

**Comment by stickhead** [comment]
does it not help?

**Comment by Nentify** [comment]
Nope

**Comment by stickhead** [comment]
well then guess we're screwed

**Comment by 6210classick** [comment]
until then just use an item buffer

**Comment by tterrag1098** [comment]
That tesserract isn't active. Activate it and conduits can connect.

**Comment by Wykks** [comment]
I'm not sure about this :

![2015-01-27_12 09 40](https://cloud.githubusercontent.com/assets/1236069/5917504/8e52525a-a61d-11e4-98bf-e755136e71a6.png)

Whereas it works fine with transfert node from Extra Utilities

**Comment by tterrag1098** [comment]
Insert mode is working because you have the tesserract in receieve only items mode. Change it to send/receive and it will connect.

**Comment by Wykks** [comment]
Okay, If I put *both* of them on send/receive it works.

A bit confusing because I don't have to do that with transfert node.

Thanks !
