### ISSUE TITLE
Ender Quarry to TE tesseract to MFR item router resulting in millions of duplicated ores.

### ISSUE THREAD

**Issue by aerialspring** [CrazyPants/EnderIO#1786]
One of my players set up an EnderIO enderquarry with Fortune III and Speed III upgrades, with a tesseract from Thermal Expansion, and an item router from Minefactory Reloaded. The quarry somehow got "stuck" on a block - no longer progressing in the mining, and is just sending fire shards (from Thaumcraft 4), TE copper, and vanilla gold. Player now has over 4 million of each. Went to the block the quarry was mining, and there is nothing there. 

We took down the quarry, but "it" is still "sending" copper and fire shards through the tesseract and item router into the chests. We then took down the receiving tesseract... and it's still going. So then we took down the item router from Minefactory reloaded, and THAT stopped the inflow. 

This is likely an MFR issue with the item router, and I will be posting this there as well, but as it involved the quarry, I figured you may want to know about this. 

No crash, so no crash report, and nothing in the console logs. 

EIO v 2.2.5.311
TE v 4.0.0B8-23
TF v 1.0.0.RC1-13
CoFH Core v 3.0.0.B9-40
MFR v 2.8.0RC6-5

**Comment by tterrag1098** [comment]
...Ender Quarry is not from EnderIO. it's from extra utilities.

**Comment by aerialspring** [comment]
omg wow. derp moment. sorry about that.

On Tuesday, January 27, 2015, tterrag1098 <notifications@github.com> wrote:

> ...Ender Quarry is not from EnderIO. it's from extra utilities.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CrazyPants/EnderIO/issues/1786#issuecomment-71590827>.
>


-- 
Noreen
