### ISSUE TITLE
ME conduit crashes game every time one is placed.

### ISSUE THREAD

**Issue by killerscorpion** [CrazyPants/EnderIO#1795]
Everytime I place a ME conduit in the world the game crashes and the world is un-loadable. I am using version 1.7.10-2.2.7.325 on Forge 10.13.2.1286
![capture](https://cloud.githubusercontent.com/assets/10732882/5929616/43c5aea4-a63a-11e4-9abf-f27a8f917284.PNG)

**Comment by tterrag1098** [comment]
#1792 #1730 #1725 #1720 and a bunch more. rv1 is NOT supported anymore. Please read past issues before reporting a new one.

**Comment by killerscorpion** [comment]
As a user, it would be nice if a feature of your mod was removed if it is no longer supported, making it less confusing for everyone. or at least disable the recipe.

**Comment by MatthiasMann** [comment]
ME conduits are still supported - but only when you use AE2 rv2

**Comment by tterrag1098** [comment]
@killerscorpion There is no way for me to reliably detect versions of the mod. It would be *nice* if users read changelogs and other issues.

**Comment by killerscorpion** [comment]
i'll upgrade to AE2 rv2, thanks for the info @MatthiasMann
