### ISSUE TITLE
Item tooltips rendered behind "Comfigure IO" in GUIs

### ISSUE THREAD

**Issue by RAnders00** [CrazyPants/EnderIO#1797]
![Picture of explaination](http://i.imgur.com/X6RhuqR.png) [Not displayed?](http://prntscr.com/5y3s44)

I think that should not be the case? The tooltip should probably go over the box?

Using EnderIO version [1.7.10-2.2.5.311](http://prntscr.com/5y3twc) `#311`
Issue [still exists](http://prntscr.com/5y417p) in [`#331`](http://prntscr.com/5y41el) (Which is the latest as of now)

[Modlist](http://prntscr.com/5y3wix)

**Comment by tterrag1098** [comment]
I'm not sure this is fixable, the tooltip rendering is almost completely out of my control.

**Comment by tterrag1098** [comment]
Fixed in a605736710202a17d1ec240e09374a675adefe45, I was wrong :P
