### ISSUE TITLE
Clarification: EnderIO and Flan's mod dual wielding

### ISSUE THREAD

**Issue by Sslazz** [CrazyPants/EnderIO#1798]
I'm experiencing an issue where EnderIO seems to be preventing Flan's mod dual-wielding. I've seen this posted on here twice already. I'm not clear on whether this a solved issue or not yet.

**Comment by tterrag1098** [comment]
I don't see how it could possibly be the fault of EIO. Flan has yet to weigh in on the issue. We have no interaction with Flan's mod so it must be a problem on his end.

**Comment by Sslazz** [comment]
Perfect, works for me. I'll resume nagging him.

Incidentally, awesome mod. Keep up the good work!
