### ISSUE TITLE
Item Conduits not connecting to MFR harvester (Ref. #862)

### ISSUE THREAD

**Issue by kenneaal** [CrazyPants/EnderIO#1801]
The bug from issue #862 seems to have been reintroduced. MFR 28.0RC6-41 and EIO 1.7.10-2.2.7.325

**Comment by tterrag1098** [comment]
I see no way this could still be a problem. The code that makes this work hasn't changed for a long time and neither has MFR.

**Comment by kenneaal** [comment]
Investigated further. I apparently used the wrong hash for the update, and the upgrade didn't actually get MFR 6-41, but MFR@1.7.10R2.8.0RC2, Updating to RC6-43 has resolved the problem.

You may now mock and Wilson-laugh as you please at me.
