### ISSUE TITLE
progress arrow in slice n splice is offset in recipies (may also be in machine too)

### ISSUE THREAD

**Issue by Ianaver** [CrazyPants/EnderIO#1802]
the arrow is offset a bit....

**Comment by MatthiasMann** [comment]
@Ianaver if you make bug reports - always include the version number you used - as the bug might have been fixed already.
If you report a visual / rendering issue - always include a screenshot - otherwise your bug report is useless.

**Comment by tterrag1098** [comment]
Fixed already.

**Comment by Ianaver** [comment]
ok, sorry about not getting the screen shot

**Comment by Ianaver** [comment]
![2015-01-29_11 33 33](https://cloud.githubusercontent.com/assets/8153290/5964795/d544882e-a7ab-11e4-93ad-62ee38c31f5c.png)
