### ISSUE TITLE
visual power indicator on the outside of capacitor banks render weird

### ISSUE THREAD

**Issue by Ianaver** [CrazyPants/EnderIO#1803]

**Comment by tterrag1098** [comment]
Same as #1804

**Comment by Ianaver** [comment]
here is the screenshot I meant to put in earlier.....
![2015-01-29_11 23 19](https://cloud.githubusercontent.com/assets/8153290/5964522/a97285fe-a7a9-11e4-95fa-89e8ad5ebe06.png)
