### ISSUE TITLE
Borders on photovoltaic cells render weird

### ISSUE THREAD

**Issue by Ianaver** [CrazyPants/EnderIO#1804]

**Comment by 6210classick** [comment]
???? no photos ? no information ?

**Comment by tterrag1098** [comment]
Seriously? Post more info and I'll reopen. For now this is absolutely useless.

**Comment by Ianaver** [comment]
and again.....
![2015-01-29_11 18 16](https://cloud.githubusercontent.com/assets/8153290/5964538/d410f052-a7a9-11e4-96ee-60f4a1550499.png)
![2015-01-29_11 18 14](https://cloud.githubusercontent.com/assets/8153290/5964541/d9aac178-a7a9-11e4-8485-b9893e5855f9.png)
