### ISSUE TITLE
Capacitor banks render weird in bad lighting conditions

### ISSUE THREAD

**Issue by Ianaver** [CrazyPants/EnderIO#1805]
using latest version (331)

![2015-01-29_11 22 36](https://cloud.githubusercontent.com/assets/8153290/5964898/9d902d10-a7ac-11e4-9b2a-bc1958d2a059.png)

![2015-01-29_11 50 53](https://cloud.githubusercontent.com/assets/8153290/5964958/3b85d934-a7ad-11e4-80c6-64a6d50428ac.png)

**Comment by tterrag1098** [comment]
Optifine?

**Comment by Ianaver** [comment]
yes

**Comment by tterrag1098** [comment]
That wasn't my question. Do you have it installed in those screenshots or not?

**Comment by Ianaver** [comment]
yes

**Comment by tterrag1098** [comment]
Then yes, it is caused by that most likely. If you have rendering issues with optifine installed ***test without it***!
