### ISSUE TITLE
Crash with EE3

### ISSUE THREAD

**Issue by Njet75** [CrazyPants/EnderIO#1806]
Crash when loading World.
Dont know if this related to Cofhlib inbedded in EE3 jar or Enderio.

crash report. http://pastebin.com/qhKUVGUn

/Njet

**Comment by MatthiasMann** [comment]
Why do you think that has anything to do with EnderIO at all? It isn't even in the stack trace.

**Comment by tterrag1098** [comment]
EE3 is failing at packets. Not EIO's fault.
