### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by AnonymousPuppy** [CrazyPants/EnderIO#1807]
I'm using a custom modpack, forge .1240, and EnderIO-1.7.10-2.2.2.300.jar. I keep getting a random crash occasionally on my server. It seems to be related to a capacitor bank, but I'm not entirely sure. 

Here is the crash report: http://pastebin.com/JyqgxWTn

Please look into this as soon as possible, thank you! :)

**Comment by tterrag1098** [comment]
You're 5 versions behind, please update. This was fixed.

**Comment by AnonymousPuppy** [comment]
My apologies, I was going to update anyways, but I was not aware that this was already fixed. Thanks for clarifying
