### ISSUE TITLE
bug with the travel enchor

### ISSUE THREAD

**Issue by MrReps** [CrazyPants/EnderIO#1814]
hello
i'had a bug, i painted my travel enchor with a block and after i painted my travel enchor with another travel enchor. i place my travel anchor and the texture was not pin up, and my game crashed.My friend was at 500meters thant me and he has crashed too. I must delet your mod and load my map for play . :/ . 
Ps: sorry for my bad english i'm french
   good luck

**Comment by tterrag1098** [comment]
Please update the mod, this was fixed
