### ISSUE TITLE
AE2 terminal connects to ME conduit backwards

### ISSUE THREAD

**Issue by BillH1949** [CrazyPants/EnderIO#1815]
![me conduit bug](https://cloud.githubusercontent.com/assets/10668463/5990015/e7139038-a952-11e4-8aaa-502348efc351.png)

Not sure whether this is an EnderIO bug or an AE2 bug.  I can't get the monitor to attach to the conduit so that the visible side is in front.

**Comment by tterrag1098** [comment]
That's not how it works, AE terminals are parts and must be on the same block as the wire. This is not currently possible with ME conduits, so you must have a block of normal ME cables to place the terminal on.
