### ISSUE TITLE
Hardcore Questing Mode

### ISSUE THREAD

**Issue by bolttanker** [CrazyPants/EnderIO#1817]
hi i have to do a quest with iron powder. the iron powder i get is from enderIO but thats the wrong one
but its the only one i can vind. how can i disable enderio iron powder so i get the good one (dont know the good iron powder mod :$)
![untitled](https://cloud.githubusercontent.com/assets/10791284/5990277/b2d6c310-a9a9-11e4-92dc-6a1a7b369543.png)

**Comment by tterrag1098** [comment]
This is not a bug on our part, your pack maker should set the quest to use ore dictionary (I assume that's a thing).
