### ISSUE TITLE
IncompatibleClassChangeError

### ISSUE THREAD

**Issue by Milobe115** [CrazyPants/EnderIO#1822]
Hello, I run a custom modpack and I get this crash when connecting my Capacitor Back to anything using an Ender IO conduit.

http://pastebin.com/tMH8GBaZ

**Comment by MatthiasMann** [comment]
You have different version of the RF API in your mod pack.
Starting with build 301 EnderIO uses the new RF API. You need to find out which of your other mods is using the old API and update these.
