### ISSUE TITLE
Cannot craft a Double-Layer Capacitor.

### ISSUE THREAD

**Issue by lAimBotl** [CrazyPants/EnderIO#1823]
I am using the crafting recipe from: http://wiki.enderio.com/Double-Layer_Capacitor#Double-Layer_Capacitor

My mods are:
CoFHCore B9-40
CoFHLib B8-34
Ender io B8-34
Extra-Utilities mod 1.7.20
nther ores c4-4
ThermalFoundation c1-13

**Comment by MatthiasMann** [comment]
The recipe has changed - you should use NEI to get the recipes. You need energetic alloy.

**Comment by lAimBotl** [comment]
wheres that?

**Comment by lAimBotl** [comment]
nevermind found it, thanks
