### ISSUE TITLE
Null pointer exceptions.

### ISSUE THREAD

**Issue by MyEternity** [CrazyPants/EnderIO#1829]
Found too many errors in game log:

java.lang.NullPointerException
	at crazypants.enderio.gui.TooltipAddera.addStirlinGeneratorTooltip(TooltipAddera.java:133) ~[TooltipAddera.class:?]

Full client logfile (packed in zip): https://www.dropbox.com/s/48825g7ubzni8hg/fml-client-latest.zip?dl=1

**Comment by MatthiasMann** [comment]
That has been fixed in build 330
