### ISSUE TITLE
EnderIO machines duped when removed with wrench

### ISSUE THREAD

**Issue by BillH1949** [CrazyPants/EnderIO#1830]
When I shift-right click on a machine with the Yeta Wrench or the AE2 network tool, I get a second copy of the item.  This happens with builds 335 and 337.

Installed mods:
AE2 rv2-beta-8
CodeChickenCore 1.0.4.29
CodeChickenLib 1.1.1.99
EnderIO 2.2.7.337
ExtraUtilities 1.2.1
Iron Chests
JABBA 1.2.0a
JourneyMap 5.0.1
Mantle 0.3.2
NEI 1.0.3.74
StevesFactoryManager A93
Tinker's Construct 1.7.10-1.8.1
WorldEdit 6.0 beta-01

**Comment by MatthiasMann** [comment]
That should be fixed in build 339
