### ISSUE TITLE
Vacuum chest crash in 340

### ISSUE THREAD

**Issue by BuckitHead** [CrazyPants/EnderIO#1831]
In latest version 339 when placing vacuum chest server crashes.
crash report:  
http://www.mediafire.com/view/zvu3o90a05mo0qe/crash-2015-02-02_22.31.32-server.txt

**Comment by tterrag1098** [comment]
Fixed via 01194de2408290109422dcbc508dc4e406a620f1

**Comment by BuckitHead** [comment]
03.02 07:23:14 [Disconnect] User BUCKITHEAD has disconnected, reason: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
03.02 07:23:14 [Server] INFO at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
03.02 07:23:14 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
03.02 07:23:14 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
03.02 07:23:14 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
03.02 07:23:14 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
03.02 07:23:14 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
03.02 07:23:14 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
03.02 07:23:14 [Server] INFO at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
03.02 07:23:14 [Server] INFO at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
03.02 07:23:14 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?]
03.02 07:23:14 [Server] INFO at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376) ~[mx.class:?]
03.02 07:23:14 [Server] INFO at crazypants.enderio.machine.vacuum.BlockVacuumChest.func_149727_a(BlockVacuumChest.java:42) ~[BlockVacuumChest.class:?]
03.02 07:23:14 [Server] INFO at crazypants.enderio.tool.ToolUtil.breakBlockWithTool(ToolUtil.java:38) ~[ToolUtil.class:?]
03.02 07:23:14 [Server] INFO at crazypants.enderio.BlockEio.removedByPlayer(BlockEio.java:88) ~[BlockEio.class:?]
03.02 07:23:14 [Server] INFO java.lang.ClassCastException: crazypants.enderio.machine.vacuum.TileVacuumChest cannot be cast to crazypants.enderio.machine.AbstractMachineEntity
03.02 07:23:14 [Server] Server thread/WARN Failed to handle packet for
