### ISSUE TITLE
Adding links to http://crafting-guide.com

### ISSUE THREAD

**Issue by andrewminer** [CrazyPants/EnderIO#1833]
I've been working on a project to make it easier to deal with complex mods (especially tech mods), and I recently added support for EnderIO. The gist of the site is that you tell it what item(s) you want to make, and it will figure out all the raw ingredients you need along with step-by-step instructions. For example, here's how you make a [Dimensional Transceiver](http://crafting-guide.com/item/dimensional_transceiver).

The maintainers of mods I've added (e.g., BuildCraft / Applied Energistics) have found it useful to include links to Crafting Guide in their official documentation, and I was hoping you would feel the same.  I'd be happy to make the changes to the wiki myself if you like the idea.

Thanks!

**Comment by KamranMackey** [comment]
Crafting Guide looks amazing. I really hope @CrazyPants & @tterrag1098 like your idea too, since they are the main coders of Ender IO. I really like the idea myself though!

**Comment by andrewminer** [comment]
@tterrag1098 — If you don't mind having them, I'd be happy to add the links myself.  Just let me know, and I'll get to work!

**Comment by tterrag1098** [comment]
I don't mind, but I'll need to add your wiki account manually.

**Comment by andrewminer** [comment]
Great, thanks!  Let me know if there's anything else I need to do.

**Comment by andrewminer** [comment]
@tterrag1098 Any update on that new account?  :-)

**Comment by andrewminer** [comment]
@tterrag1098 Sorry to be a bother, but I'm kinda stuck without that account...  :-(

**Comment by tterrag1098** [comment]
Agh, sorry I keep forgetting. You should now have an email on your @mac.com email (the one listed on your github account).

**Comment by andrewminer** [comment]
Awesome, thanks!

**Comment by andrewminer** [comment]
Should be all set!  I added a link for each item, and fixed up a few issues I ran across while doing so.  Thanks again!
