### ISSUE TITLE
Wither skeleton problem

### ISSUE THREAD

**Issue by JadeCreeper** [CrazyPants/EnderIO#1835]
There are normal skeletons (With nothing in there hands) in the nether (In fortresses) that according to WAILA are wither skeletons from Ender IO. They drop arrows and bones, but not normal skeleton skulls nor do they drop wither skeleton skulls (I have tested this with a TCoN cleaver with full beheading). Furthermore, they spawn in Huge numbers, i have found groups of up to 30+ of them in one spot.

Tested with the latest version of Ender IO from Cursforge.

**Comment by MatthiasMann** [comment]
First - always include the version number.
Try the latest build 340 from the ci server.

**Comment by tterrag1098** [comment]
This is already reported
