### ISSUE TITLE
Wireless charger 2x dupe when removed with wrench

### ISSUE THREAD

**Issue by BillH1949** [CrazyPants/EnderIO#1836]
Using build 340, removing the wireless charger with the yeta wrench causes two additional chargers to drop.  Removing other machines appears to be fine (I tested with the Soul Binder and got no dupes).

**Comment by tterrag1098** [comment]
Fixed via https://github.com/CrazyPants/EnderIO/commit/d3417225d1e7c1520a41de4644ce53d18e4ff96f
