### ISSUE TITLE
Stirling Generator crash

### ISSUE THREAD

**Issue by edwardsdean** [CrazyPants/EnderIO#1837]
When i use the Stirling generator in to following set up http://imgur.com/Q9ONqec , when i put coal blocks in it crashes my world and i am unable to load the world again.

crash log - http://pastebin.com/wHCz0Y1f
enderio version - 1.7.10-2.2.7.325
forge - 10.13.2.1291
java - 1.8.0_25

**Comment by MatthiasMann** [comment]
You have different versions of the RF API loaded. EnderIO uses the new RF API starting with build 301. You need to upgrade the other mods to also use the new RF API.
