### ISSUE TITLE
Travel Anchor/Vacuum Chest removal crash 

### ISSUE THREAD

**Issue by BuckitHead** [CrazyPants/EnderIO#1840]
So after update 340 i can now place the vacuum Chest. When it comes to removing it or the travel anchor it crashes the client. I used a pick, wrench and hand to try and remove, and all cause the client to crash. 

Crash from server console  for Travel Anchor( I posted the crash for the Vacuum Chest in #1831)

03.02 18:28:56 [Server] Server thread/INFO BUCKITHEAD left the game
03.02 18:28:56 [Disconnect] User BUCKITHEAD has disconnected, reason: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
03.02 18:28:56 [Server] INFO at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
03.02 18:28:56 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
03.02 18:28:56 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
03.02 18:28:56 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
03.02 18:28:56 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
03.02 18:28:56 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
03.02 18:28:56 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
03.02 18:28:56 [Server] INFO at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8) ~[ji.class:?]
03.02 18:28:56 [Server] INFO at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53) ~[ji.class:?]
03.02 18:28:56 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:489) ~[nh.class:?]
03.02 18:28:56 [Server] INFO at net.minecraft.server.management.ItemInWorldManager.func_73074_a(ItemInWorldManager.java:186) ~[mx.class:?]
03.02 18:28:56 [Server] INFO at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:296) ~[mx.class:?]
03.02 18:28:56 [Server] INFO at net.minecraft.server.management.ItemInWorldManager.removeBlock(ItemInWorldManager.java:247) ~[mx.class:?]
03.02 18:28:56 [Server] INFO at crazypants.enderio.BlockEio.removedByPlayer(BlockEio.java:88) ~[BlockEio.class:?]
03.02 18:28:56 [Server] INFO java.lang.ClassCastException: crazypants.enderio.teleport.TileTravelAnchor cannot be cast to crazypants.enderio.machine.AbstractMachineEntity
03.02 18:28:56 [Server] Server thread/WARN Failed to handle packet for xxx.xxx.xxx.xxx

**Comment by tterrag1098** [comment]
Fixed via https://github.com/CrazyPants/EnderIO/commit/d3417225d1e7c1520a41de4644ce53d18e4ff96f

**Comment by BuckitHead** [comment]
Thanks Again......
