### ISSUE TITLE
Capacitor banks lose their energy when wrenched and Waila not updating

### ISSUE THREAD

**Issue by Yucca86** [CrazyPants/EnderIO#1844]
I updated to the latest 341 build of EnderIO and now if I wrench capacitorbanks to move them, they lose their stored energy. Build 340 was fine.
And this is on a server enviroment.
And in build 340 or might have been couple builds earlier, the RF counter in Waila doesn't update the stored energy until I open the GUI of the capacitor bank.
In all cases the scenario has been that I am using a tier 1 capacitorbank to power a Progressive Automation miner.

**Comment by tterrag1098** [comment]
Half fixed via https://github.com/CrazyPants/EnderIO/commit/10af591ceeea80b992bc590c975c0363697098b0

**Comment by tterrag1098** [comment]
And fixed

**Comment by Yucca86** [comment]
Thanks and keep up the good work
