### ISSUE TITLE
Energy Conduit Crash

### ISSUE THREAD

**Issue by DStrand1** [CrazyPants/EnderIO#1851]
Whenever I place an energy conduit, it crashes immediately, and this is on version 2.2.8.342

http://pastebin.com/MHy7rzf1

**Comment by DStrand1** [comment]
Also when I went back onto the world, the conduit was there, but when I looked at it, it crashed again, so maybe that's the issue.

**Comment by tterrag1098** [comment]
Your forge is very old, please update.

**Comment by tterrag1098** [comment]
I've added a hard dep on forge 1234+ for the future.

**Comment by tterrag1098** [comment]
Scratch that, I'm reverting the change because cauldron only works with 1231...

**Comment by nister6000** [comment]
Caludron 213 use 1240
