### ISSUE TITLE
Server crash with chisel 2

### ISSUE THREAD

**Issue by wxnko** [CrazyPants/EnderIO#1866]
Here's crashlog http://pastebin.com/FS2Ui3TJ
I don't know what players do. So i cant explain how it crashed.

**Comment by MatthiasMann** [comment]
This looks like blocks or tile entities have been moved around. Doesn't look like an EnderIO issue.

**Comment by tterrag1098** [comment]
This is a bug with chisel, don't use the presents. They are fixed in dev builds though.
