### ISSUE TITLE
Ghost blocks/wither skeleton spawning issue

### ISSUE THREAD

**Issue by devryb** [CrazyPants/EnderIO#1878]
With build 2.2.7.325 we are getting a really weird problem.
It seems ghost blocks started spawning and within those blocks Wither Skeletons spawn in mass numbers when the player is outside of render distance from them.
Inside the stone outline of the ghost blocks no blocks can be placed within either.

http://puu.sh/fCoN1/a7c1dd6db9.jpg
http://puu.sh/fCoYn/f81ce66841.jpg

This appears to be a combination of https://github.com/CrazyPants/EnderIO/issues/1761 and https://github.com/CrazyPants/EnderIO/issues/1336 but they should be fixed in this version should they not?

**Comment by tterrag1098** [comment]
No, this issue was fixed in 2.2.8, which you should try (it is the latest release). Try that and report back.
