### ISSUE TITLE
Request databank item filter

### ISSUE THREAD

**Issue by Flukethoughts** [CrazyPants/EnderIO#1887]
Two items request
Digital item filter card
Digital item filter machine

The digital Item filter card would be an item you placed in item conduits fluid conduit and so on. That would allow up to 64 items to be added to a single filter list.

You would need to craft a machine to set the digital filter on each card the card itself wouldn't know rather to black list or white list it would simple hold the item ids/names of the blocks put inside of it using the digital filter machine. 

The user would then be able to craft the digital item filter card and edit it with the machine to allow him to only have to run one item conduit through the whole house. 

The machine would have to have a recipe that is difficult to craft but easy to use. 

Digital item filter could use a capacitor and ender dust or other things to make it.

**Comment by MatthiasMann** [comment]
Umm - if you just want a larger filter - use the exiting item filter.
That can learn items from inventories (either via the conduit GUI or by shift right clicking the filter on a chest etc).

**Comment by Flukethoughts** [comment]
yea I know about that item filter I was just talking about the idea of expanding one. but thanks
