### ISSUE TITLE
Item conduits not pulling from Forestry apiarist chests

### ISSUE THREAD

**Issue by Megistus** [CrazyPants/EnderIO#1903]
Used to work with previous forestry apiarist chest, but with forestry_1.7.10-3.4.0.7 it has ceased to work. I am also using EnderIO-1.7.10-2.2.8.344

**Comment by tterrag1098** [comment]
Um, why did you open this twice? #1883

**Comment by Megistus** [comment]
I had not meant to ... looks as if the posting mechanism hiccuped somehow as I believed I had only posted once. Sorry
