### ISSUE TITLE
Pressurized fluid conduit overflows TE magmatic dynamo's maximum capacity

### ISSUE THREAD

**Issue by WillemWillemWillem** [CrazyPants/EnderIO#1904]
When I connect a pressurized fluid conduit to a Thermal Expansion magmatic dynamo, the magmatic dynamo's lava buffer jumps to huge negative millibucket values, which gets more negative very fast. It (the dynamo) also stops working after about 0,2 seconds.

I play TPPI 1.1.2 with the FTB launcher, on a 2GB server hired from SpartanHost. The world where these dynamos are placed in is a randomly generated Mystcraft world with these specific chunks chunkloaded with a chunkloader. I tried a setup with the conduit not crossing chunk bounderies but that didn't help.

If there's anything more I can do to help I'd be glad to. At the moment I just use TE Fluiducts instead, but I'd really like to completely replace them with EnderIO conduits.

![untitled](https://cloud.githubusercontent.com/assets/4689687/6147951/23e4c7ae-b1fd-11e4-8899-472c4d7887fc.png)
![untitled](https://cloud.githubusercontent.com/assets/4689687/6147939/fc125f5c-b1fc-11e4-9676-c1fdf74cdd88.png)
![untitled](https://cloud.githubusercontent.com/assets/4689687/6148000/c4a0c940-b1fd-11e4-9c23-169dd9154d8e.png)

**Comment by WillemWillemWillem** [comment]
In case it's relevant: the lava is being generated by MFR lava fabricators connected to pressurized fluid conduits in insert mode, connected to a fluiduct (I was short on conduits and so far they have proven to be unreliable for inserting stuff into machines).

![untitled](https://cloud.githubusercontent.com/assets/4689687/6148065/5eee7b5a-b1fe-11e4-9e3a-dbb8e52bb017.png)

**Comment by tterrag1098** [comment]
1.6 is very outdated, and this was a bug in TE. As far as I know it is
fixed in 1.7
