### ISSUE TITLE
Conduit texture issue using latest version

### ISSUE THREAD

**Issue by PsionicArchon** [CrazyPants/EnderIO#1909]
I'm still getting the conduit texture bug using the latest version of EnderIO available on the jenkins.

EnderIO Version: 2.2.8.348

All conduits are set to insertion mode.. I think.

Example: http://i.imgur.com/7KqNUlZ.png

It's g-mod in Minecraft.

**Comment by JasonMcRay** [comment]
Same issue as in https://github.com/CrazyPants/EnderIO/issues/1889.

**Comment by tterrag1098** [comment]
Yep, duplicate
