### ISSUE TITLE
[Enhancement request] Allow The Vat to be muffled by Sound Muffler

### ISSUE THREAD

**Issue by BillH1949** [CrazyPants/EnderIO#1912]
I currently have 8 vats in my power room creating hooch and rocket fuel, and they are quite loud.  I tried using the ExtraUtilities Sound Muffler to block the noise, but the sound doesn't appear to be within an 8-block radius of the the actual vat.  It's a small quality-of-life fix, but I'd appreciate it.

**Comment by 6210classick** [comment]
you can either change

D:machineSoundVolume=1.0 or B:useMachineSounds=false to completely disable all machine sounds

**Comment by BillH1949** [comment]
Thanks for the tip!
