### ISSUE TITLE
Crash Ender IO 1.7.2

### ISSUE THREAD

**Issue by ArtutoGamerYT** [CrazyPants/EnderIO#1929]
The Crash are in pastebin: http://pastebin.com/JBquVi2b

Was occur in the Mojang Screen.

**Comment by MatthiasMann** [comment]
You are using a very old version - I suggest you upgrade to Minecraft 1.7.10 and EnderIO 2.2.8 build 349

**Comment by TheJulianJES** [comment]
I agree.

**Comment by ArtutoGamerYT** [comment]
1.7.10 is Laggy and the worse Minecraft Version

**Comment by ArtutoGamerYT** [comment]
Thanks... I go to delete Ender IO from my .minecraft mods foleder. :-1: :(

**Comment by ArtutoGamerYT** [comment]
If you have a solution. PM me :)

**Comment by tterrag1098** [comment]
Actually 1.7.10 with the latest forge builds is MUCH less of a resource hog than 1.7.2. But suit yourself.

**Comment by tterrag1098** [comment]
Yeah don't put [UNRESOLVED] in the title, this issue IS RESOLVED, you are just too out of date to have the fix.
