### ISSUE TITLE
ME conduits disconnecting from AE cables

### ISSUE THREAD

**Issue by AiwendilCiunio** [CrazyPants/EnderIO#1930]
I noticed this happens whenever our server gets restarted, and each time chunks are unloaded (logging off etc). 

ME conduits disconnect themselves from AE cables, cutting off portions of the network. This also happens visually - conduit connector disappears and also AE cable changes appearance (looses the "branch", as if nothing was connected).

This can be fixed by replacing the AE cable (conduit connector doesn't reappear, but everything works), but not by replacing the ME conduit (doing so just breaks the AE cable it's connecting to).

Using AE2 rv2 beta 7  and EiO 2.2.7.329
Server is using Cauldron

**Comment by MatthiasMann** [comment]
You are using an old EnderIO version - all known ME conduit issues have been fixed in EnderIO 2.2.8 build 349

**Comment by TheJulianJES** [comment]
I agree with @MatthiasMann, he fixed all ME Conduit bugs, you can download the version: ci.tterrag.com/job/EnderIO/lastSuccessfulBuild/

**Comment by AiwendilCiunio** [comment]
Thank you, will update then.

**Comment by TheJulianJES** [comment]
Okay, if this is fixed, then please close this issue.
