### ISSUE TITLE
Random Server Lag Spikes. Logs within. 

### ISSUE THREAD

**Issue by Cuppycake** [CrazyPants/EnderIO#1936]
I am having these random lag spikes on my server. They don't last a long time but they an extreme annoyance and shouldn't be happening. Anything I catch in the log seems to point to enderIO and or Extra Cells. Ill drop my pastebins here. 

http://pastebin.com/ELfZGbTg
http://pastebin.com/KgAwK8ht
http://pastebin.com/kVpCPbnd

**Comment by tterrag1098** [comment]
This is an extra cells bug, the error originates there.
