### ISSUE TITLE
Game still crashing when placing me conduits

### ISSUE THREAD

**Issue by l3CY** [CrazyPants/EnderIO#1938]
Game crashed instantly after placement of a me cable.  The only change made to enderIO's configs were conduit's width set to 0.8.

The world can no longer be opened.

Crash report
http://openeye.openmods.info/crashes/1db633c593f27ebb19cd72d09d0fa7b1

**Comment by MatthiasMann** [comment]
EnderIO no longer support AE2 rv1 or older (as written in the Release Notes)
