### ISSUE TITLE
Conduit arrows rendering bug

### ISSUE THREAD

**Issue by iTpyn** [CrazyPants/EnderIO#1939]
EnderIO conduits doesn't render properly, connectors are blinking, depending on player's point of view. Tested all available 2.2.8 builds. Downgrading to 2.2.7.325 fixes the problem 
http://i.imgur.com/58vQslH.png
http://i.imgur.com/kW4CBgI.png
http://i.imgur.com/abrIhbi.png

**Comment by HenryLoenwind** [comment]
See also #1915

**Comment by tterrag1098** [comment]
Indeed, duplicate of #1915
