### ISSUE TITLE
Iguana+Ender IO

### ISSUE THREAD

**Issue by Teleclast** [CrazyPants/EnderIO#1945]
I'm not sure if this is the right place to post it, but I figured I'd try here and Iguana. I'm using Infinity's versions, but I'm trying a few things on my side including updating to the most recent version of Ender IO, and Iguana.

http://pastebin.com/Qyvzfdp3

**Comment by MatthiasMann** [comment]
That issue has been fixed in build 326.
Update EnderIO - best to 2.2.8 build 349 which is on Curse.

**Comment by Teleclast** [comment]
Thank you very much, I did indeed update it and found it out right before coming to post a response here.
