### ISSUE TITLE
Shift-clicking item into Dark Steel Anvil temporarily dupes item

### ISSUE THREAD

**Issue by BillH1949** [CrazyPants/EnderIO#1947]
If I shift-click an item into the anvil, it appears both in my inventory and in the anvil.  Once I complete the repair and close the UI, my inventory shows one item again.  I'm using build 350.

**Comment by HenryLoenwind** [comment]
As far as *I* know, that's a vanilla bug.

**Comment by tterrag1098** [comment]
Yes, yes it is
