### ISSUE TITLE
Crashing when removing Mekanism's Cable from capacitor bank

### ISSUE THREAD

**Issue by FagerholmS** [CrazyPants/EnderIO#1949]
Client doesn't crash, only server will.
Crash report: http://pastebin.com/pNNhKhz5

**Comment by MatthiasMann** [comment]
Update EnderIO - this has been fixed a long time ago.

**Comment by FagerholmS** [comment]
Oh, im sorry. Thanks!

**Comment by HenryLoenwind** [comment]
No reason to be sorry. I'd prefer 100 reports for an already fixed bug to hearing one day in a youtube video "don't do that, it's known to crash and has been for years"... ;)
