### ISSUE TITLE
occasional NPE on attempting to place ME conduit into bundle

### ISSUE THREAD

**Issue by Katalliaan** [CrazyPants/EnderIO#1951]
[Crashlog](http://pastebin.com/iB7L9j9A)

On EnderIO-1.7.10.2.2.8.343.jar

It seems to be limited to blocks that have had an ME conduit in the bundle before. I haven't found a way to reliably create a block that's in this state, although once it is in such a state it will remain so until all conduits in the bundle are removed.

**Comment by MatthiasMann** [comment]
That has been fixed in 2.2.8 build 349

**Comment by Katalliaan** [comment]
All right, thanks. Couldn't find a build-to-build changelog to see if it had been addressed.

**Comment by MatthiasMann** [comment]
A very detailed release note is here:
https://github.com/CrazyPants/EnderIO/blob/master/ReleaseNotes.txt
