### ISSUE TITLE
Killer Joe being deleted from world

### ISSUE THREAD

**Issue by Hazado** [CrazyPants/EnderIO#1955]
Here is the error from my server log, doesnt crash the server.
Killer Joe is there one minute, gone the next.

http://pastebin.com/8esHmMAK

**Comment by HenryLoenwind** [comment]
(5 second diagnosis) This happened when the KillerJoe told a Pneumaticraft entity that it killed it, in the pneumaticCraft.common.EventHandlerPneumaticCraft.onEntityDeath() method. I suspect the bug lies there.

**Comment by tterrag1098** [comment]
Yes, the bug is there, not here.
