### ISSUE TITLE
Item Conduit connects to capacitor bank

### ISSUE THREAD

**Issue by BillH1949** [CrazyPants/EnderIO#1957]
Not a huge deal, but it doesn't really make sense either.

**Comment by tterrag1098** [comment]
Why not? Capacitor banks hold items.

**Comment by BillH1949** [comment]
Huh?! How can you tell if there are items in a capacitor bank?

**Comment by tterrag1098** [comment]
What? Just...open it?

**Comment by BillH1949** [comment]
Fair enough.
