### ISSUE TITLE
[2.2.8.349] Dark Steel Pickaxe right click on vacuum chest -> server crash

### ISSUE THREAD

**Issue by ruyanve** [CrazyPants/EnderIO#1963]
Not much more to say... Fully charged Dark Steel Pickaxe, right click on vacuum chest. Client was fine, server shut down.
Forge 10.13.2.1291

Full crash log: http://pastebin.com/qvhAtung

Have a good day! :)

**Comment by HenryLoenwind** [comment]
Already been fixed in #1895 for the upcoming 2.2.9 release.

Thanks for the report.

**Comment by ruyanve** [comment]
Hehe damn I missed that one, sorry!
