### ISSUE TITLE
Soul Binder recipes config

### ISSUE THREAD

**Issue by quentinrossetti** [CrazyPants/EnderIO#1965]
Hi,

Is there a way to customize Soul Binder recipes like we can with the other machines (`VatRecipes_User.xml`) ?

**Comment by MatthiasMann** [comment]
Yes, but only via IMC:
https://github.com/CrazyPants/EnderIO/blob/master/src/main/java/crazypants/enderio/EnderIO.java#L687

**Comment by quentinrossetti** [comment]
Ok, thanks.
Could you provide me with a simple example of how to remove/add a recipes, or point me to an example ?
