### ISSUE TITLE
TE/EIO Crash

### ISSUE THREAD

**Issue by Nentify** [CrazyPants/EnderIO#1969]
http://pastebin.com/MYA75x2a

Crashing server on start up, any idea what's causing it?

**Comment by tterrag1098** [comment]
@skyboy

**Comment by skyboy** [comment]
Some block on the other side of a tesseract returned a null where it shouldn't have.

**Comment by tterrag1098** [comment]
Returned a null from what?

**Comment by Nentify** [comment]
Removing and re-adding EIO fixes this issue, although I'm not sure if this will cause issues with my setup.

**Comment by Nentify** [comment]
Seems it does. Will have to see what else I can do.

**Comment by KingLemming** [comment]
I'm curious - what is the Tesseract connecting to on the other end? That is what is really at at fault here.

**Comment by Nentify** [comment]
I don't know what the issue was. The issue hasn't re-occured so far though. There are thousands of tesseracts on the map, so it's difficult to track down without block coords in the log. :P

I have a backup of the world if you're interested in finding out though.
