### ISSUE TITLE
Client Crash when ME Conduits shall connect

### ISSUE THREAD

**Issue by c0nnex** [CrazyPants/EnderIO#1973]
When I try to connect a ME Conduit to anything other (even another ME Conduit) the client crashes.
AE v2beta8 is installed. EnderIO{1.7.10-2.2.8.344}

Crashreport: http://c0nnex.de/dl/crash-2015-02-20_16.20.47-client.txt

**Comment by MatthiasMann** [comment]
Update to EnderIO version 2.2.8 build 349 available on Curse
