### ISSUE TITLE
ME conduits destroy AE2 blocks

### ISSUE THREAD

**Issue by Divran** [CrazyPants/EnderIO#1974]
I've the weirdest bug. When I place ME conduits adjacent to AE2 blocks, the AE2 blocks get destroyed. This makes it completely impossible to connect anything. I have found that removing and replacing every single conduit sometimes fixes it (but not always). Unfortunately I don't really have any more info to give you, since it isn't my server. Let me know if I can help somehow.

EDIT: It seems to magically fix itself if I disconnect the ME controller from the power source.

**Comment by MatthiasMann** [comment]
Update EnderIO version to 2.2.8 build 349 available on Curse.

**Comment by Divran** [comment]
We're using the direwolf20 pack, so we would have to get him to update it I guess. How do I know which version the server has installed now?

**Comment by MatthiasMann** [comment]
You look into your mod folder - because client & server must use the same version.

**Comment by Divran** [comment]
Apparently direwolf20 is using `EnderIO-1.7.10-2.2.5.311.jar`

**Comment by Divran** [comment]
Alright I've sent a message to direwolf20 via youtube. Hopefully he'll respond.

Until then, another issue I've noticed is that when I do manage to connect the cables, the ME system doesn't recognize my interfaces. The indicators on them are supposed to turn pink-ish and then blue to indicate they've been connected, but they just stay black. I've had to disconnect the cable, reconnect it, disconnect the ME Controller from its power supply, reconnect it, etc etc multiple times until it just randomly works for no reason.

If you know anything about what might cause this, it'd be great if you could fix it. Or maybe you've already fixed it in the latest version. In any case, thanks for your help.

**Comment by MatthiasMann** [comment]
Your version is out dated - update to build 349 before complaining.

**Comment by Divran** [comment]
I know I should. I'm just reporting these issues here for myself as much as for you. I know I'll forget about them by the time we've updated, so now I know what to test after we have updated. Then I'll get back to you if it still happens.

**Comment by MatthiasMann** [comment]
The ME conduits had been completely rewritten - any report from that old version is useless.

**Comment by Divran** [comment]
Alright, then. I'll close this issue for now. If I find any of these bugs with the latest version, I'll reopen it.
