### ISSUE TITLE
Server crash with painted glowstone and carpenters

### ISSUE THREAD

**Issue by Neodark7** [CrazyPants/EnderIO#1976]
http://pastebin.com/Z4LbSyEQ

**Comment by 6210classick** [comment]
are you using version 2.2.8 349 ??

so what did you do exactly that caused the crash ? did you use painted glowstone on a carpenter block or ??

**Comment by Neodark7** [comment]
nope i don't, it happens on server stat when i update all the cofh mods to latests versions
i use EnderIO-1.7.10-2.2.8.0.a5ff6dd an equivalent of the 350/351 build i guess

**Comment by MatthiasMann** [comment]
I don't see how this is caused by EnderIO - maybe your world got corrupted?

**Comment by Neodark7** [comment]
works fine with the actual version of the cofh mods it happen only when i upload them

**Comment by MatthiasMann** [comment]
Try downgrading cofh again and see if it stops crashing.

In any case EnderIO does not depend on cofh - and I don't think carpenters does either. So I don't see why this should have any effect.

**Comment by Neodark7** [comment]
apperently it's fixed... with the new "stable" versions of all cofh mods it start fine :) weird issue

**Comment by Neodark7** [comment]
Fixed this need to backdate all cofh mods to december versions and update again with stable ones

**Comment by Neodark7** [comment]
Fixed this need to backdate all cofh mods to december versions and update again with stable ones
