### ISSUE TITLE
Spawn rate not equal for soul vials

### ISSUE THREAD

**Issue by krakentoa** [CrazyPants/EnderIO#1977]
Creating soul vials is much less efficient than the spawning mode. Intended?

**Comment by 6210classick** [comment]
you can increase the spawning rate by adding either a Double-Layered or Octadic capacitor if you still think it's still too low you can change the spawning rate in the config

yeah i believe it's intended mainly so you can automate the production of Ender Crystals

**Comment by krakentoa** [comment]
I know I can, but from reading the code (and from experience) it will still be slower than using the powered spawner in "Spawn" mode.

**Comment by tterrag1098** [comment]
Yes it's intended to be more expensive.
