### ISSUE TITLE
Crash with Minefactory reloaded Ender IO version 344

### ISSUE THREAD

**Issue by jamzam90** [CrazyPants/EnderIO#1981]
The 344 version of enderio is crashing with minefactory reloaded version
2.8.0RC6-5
I am unable to start the game and the crash report is saying java.lang.NoClassDefFoundError: Lcrazypants/enderio/conduit/BlockConduitBundle;

Crash Report
http://pastebin.com/yDtuUw4j

**Comment by tterrag1098** [comment]
This bug is caused by another mod shipping an incomplete MFR API, I can't say which. You need to remove other mods until the issue goes away. This is not a problem with EnderIO.

**Comment by spidey1958** [comment]
Actually getting same error but seems to be new version of thermal expansion and thermal dynamics causing issue

**Comment by SwatKid** [comment]
getting same issue D:

**Comment by bigbantha** [comment]
If that's the case, then why does it include Ender IO in the report?

**Comment by tterrag1098** [comment]
Because that mod shipping the incomplete API causes certain API classes EnderIO uses from MFR to not be available. Basically, other mod messes up but it looks bad on EnderIO's side. Sucks, right?

**Comment by MoxieGrrl** [comment]
Both of those crashes are using a relatively old version of MFR. Update to the newest version and see if the crash still persists.

http://minecraft.curseforge.com/mc-mods/66672-minefactory-reloaded/files/2228271/download

**Comment by K-4U** [comment]
Just updated MFR to that version. crash still persists.

**Comment by MoxieGrrl** [comment]
Well, this may help: I force crashed to grab my modlist so you guys could check yours against it.

http://pastebin.com/S7rNkqmQ

**Comment by b0bst3r** [comment]
Ok bit of testign for you tterrag, I get this issue with only the following mods installed:

CoFHCore-[1.7.10]3.0.0RC1-186.jar
CoFHLib-[1.7.10]1.0.0B9-113.jar
EnderIO-1.7.10-2.2.8.349.jar
MineFactoryReloaded-[1.7.10]2.8.0RC7-72.jar
ThermalDynamics-[1.7.10]1.0.0RC1-69.jar
ThermalExpansion-[1.7.10]4.0.0RC1-120.jar
ThermalFoundation-[1.7.10]1.0.0RC2-54.jar

Running under forge-1.7.10-10.13.2.1236-universal.jar

**Comment by KingLemming** [comment]
http://puu.sh/g7KCi/9eea54682a.png

Zero issues for me.

**Comment by K-4U** [comment]
Update to Forge 1291. That fixed it for me.
TD requires forge 1291 on the client.

**Comment by b0bst3r** [comment]
What Forge version is that KL, I tried 1236 and it crashed (actually no idea why ATLauncher puts 1236 in as "latest") tried recommended Forge (1230 also seems really old) and that has an issue with FML. So manually downloaded 1291 and all works fine.  So def seems Forge related.

**Comment by evenas98** [comment]
fixed by updating to latest forge
