### ISSUE TITLE
Killer Joe and Dimensional Transciever stop functioning

### ISSUE THREAD

**Issue by LookitWookiee** [CrazyPants/EnderIO#1990]
Killer Joe stops killing mobs after only using a quarter tank of nutrient distillation and will not work again. I just have to make a new one. Dimensional Transciever worked once. When I tried to move one of the units I could not reestablish a connection even with new transcievers or channels.

**Comment by LookitWookiee** [comment]
One more thing. I use Ubuntu and Windows. The problem has persisted across multiple instances on both OS.

**Comment by 6210classick** [comment]
both Killer Joe & Zombie generator requires you to have at least 75% of nutrient distillation any lower it will stop functioning

the Dimensional Transciever needs power to work each one have 250k internal storage and uses 10rf/tick

if the problems still occurs what version of EIO are you using ? provide more information

**Comment by tterrag1098** [comment]
What @6210classick said is accurate. The killer joe needs to be filled up to the red line in the GUI to function and the DimTrans needs constant power to keep a channel active.
