### ISSUE TITLE
EnderIO overriding AE2's silicon, cannot find fix.

### ISSUE THREAD

**Issue by FagerholmS** [CrazyPants/EnderIO#1995]
http://i.imgur.com/CjOEn2T.png server and client side. Still not work, is there something in enderio's config?

**Comment by MatthiasMann** [comment]
EnderIO registers it's own silicon in the oredict - and does nothing to AE2's.
But if AE2 detects other mod's silicon it will disable it's own recipe - not an EnderIO issue.

**Comment by 6210classick** [comment]
if you want EIO to use it's own dust & silicon .. etc

replace OreDictionaryPreferences_User with this one

https://www.dropbox.com/s/5u0cui5sp8yr165/OreDictionaryPreferences_User.xml?dl=0
