### ISSUE TITLE
Placing ME Conduit in facade with power conduit causing crash and unenterable world

### ISSUE THREAD

**Issue by droctogonapus** [CrazyPants/EnderIO#2000]
I have seemed to have run into an error where I attempted placing a me conduit inside a facade with a power conduit already inside the facade.  The facade was painted with the futuristic armor from chisel 2.  I am currently unable to get back into the world.

Using Ender io: 2.2.8.349
Forge: 10.13.2.1230

Here is the crash log
Crashlog: http://pastebin.com/MERa9KGa

**Comment by tterrag1098** [comment]
AE rv1 is no longer supported

**Comment by droctogonapus** [comment]
Never thought about updating AE2.  All seems to be working now
