### ISSUE TITLE
[Suggestion] Add Computer Craft support  for Dimensional Transceiver.

### ISSUE THREAD

**Issue by grundyboy34** [CrazyPants/EnderIO#2003]
I had an idea for a build here recently but was disappointing to see that dimensional transceivers aren't a peripheral in computer craft. I'd very much like to be able to remotely change the channel and other options of the transceiver via computers.

**Comment by Vexatos** [comment]
Check out the mod [Computronics](http://wiki.vex.tty.sh/wiki:computronics). It adds peripherals to pretty much every block in EnderIO.

**Comment by tterrag1098** [comment]
What @Vexatos said. I fully recommend that mod for all CC/EIO interaction, we won't be implementing anything of the sort natively.
