### ISSUE TITLE
Issue with new COFH team updates.

### ISSUE THREAD

**Issue by Leganie** [CrazyPants/EnderIO#2004]
The crash report focuses on something with the MFR rednet api. here is the report. This pack of mine worked fine till I updated COFH mods I use. MY test server loads fine but the client has this issue for some reason.

http://pastebin.com/5feSHYbu

Hope this is a simple fix and seeing as their api's are needed for a bunch of mods these days I didn't know where else to report this. PM me directly if you need a ftb pack code to help you as this is a private pack I made for me and some friends.

**Comment by Adaptivity** [comment]
#1981 #1982 #1983 #1985 #1988 #1989 #1993 #1997
