### ISSUE TITLE
Crash when using new CoFHCore

### ISSUE THREAD

**Issue by DragonicNick** [CrazyPants/EnderIO#2006]
When I use the newest CoFHCore-[1.7.10]3.0.0RC2-195 , it crashes and won't start the game.
I would like this new version because its required for Themal Dynamics.

Crash log:
http://pastebin.com/T448pTMk

I don't know if I did something wrong?
Can you help me with this?

**Comment by HenryLoenwind** [comment]
See #1981 #1982 #1983 #1985 #1988 #1989 #1993 #1997 #2004

**Comment by DragonicNick** [comment]
Updating forge fixed it for me. Thanks!
