### ISSUE TITLE
Crash every 30 minutes or so (at crazypants.enderio.machine.painter.PainterUtil.getTooltTipText(PainterUtil.java:61) ~[PainterUtil.class:?])

### ISSUE THREAD

**Issue by superpatosainz** [CrazyPants/EnderIO#2007]
Running everything at its latest version, I experience a crash from EnderIO in the middle of my play session, which, in a nutshell is:

    [00:17:43] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.ItemTooltipEvent@4e1fe33b:
java.lang.NullPointerException
    at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427) ~[add.class:?]
    at crazypants.enderio.machine.painter.PainterUtil.getTooltTipText(PainterUtil.java:61) ~[PainterUtil.class:?]
    at crazypants.enderio.conduit.facade.ItemConduitFacade.addBasicEntries(ItemConduitFacade.java:175) ~[ItemConduitFacade.class:?]

Here's the full log: <http://pastebin.com/MWDc2GFy> and apparently I'm not the only one experiencing this: <http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291161-1-7-1-6-ender-io-how-many-pipes-in-one-block?comment=1580>

**Comment by HenryLoenwind** [comment]
Did you paint a conduit facade in the Painting Machine? If yes, as what block? Is it in your inventory? Also, I see "handleKeyboardInput" in your trace, which key did you press?

**Comment by superpatosainz** [comment]
@HenryLoenwind My house uses a lot of facades, but I have none in my inventory when it crashes (and my painting machine is empty, too). And I can recall with much precision what key I pressed but I can safely say it's not always the same for these crashes, sometimes it's w for forwards, e for inventory, etc. I think NEI handles all of these (and mouse movement) in the same routine.

I think your most recent commit may fix this, I'll try it as soon as jenkins builds it.

**Comment by HenryLoenwind** [comment]
I'm trying to understand why and when this error happens. If it was one block that never had an item, then you would crash every time you put your mouse over the painted facade. So something must be funny in this special case. Also, it should be impossible to get this crash unless you are in any kind of GUI screen. Tooltips are only rendered when there is a mouse cursor.

On a second look, that trace looks like you've been in an AE GUI screen, maybe an ME terminal. (Same with the crash from the forums.) Do you have (painted) facades in your ME system?

My current suspicion is that AE is creating the ItemTooltipEvent different than Forge in vanilla GUIs.

**Comment by superpatosainz** [comment]
Can confirm; I do have lots of painted facades stored in my ME system.

**Comment by superpatosainz** [comment]
Will test asap.

**Comment by tterrag1098** [comment]
Whenever I tell it to :P

**Comment by superpatosainz** [comment]
@tterrag1098 are there enough commits to warrant a new build ;)?

**Comment by superpatosainz** [comment]
@tterrag1098 Just built it myself via gradle, everything's working fine, the crash is gone. gg @HenryLoenwind .

**Comment by HenryLoenwind** [comment]
Thanks for the feedback. So AE2 *is* doing something weird to the environment here...

**Comment by superpatosainz** [comment]
@HenryLoenwind is there any chance AE2 could cause more issues for other mods?... what's the _root cause_ of all this?

**Comment by HenryLoenwind** [comment]
Yes, it could be possible. I went through the code line by line and with just Vanilla, Forge and Ender IO that variable cannot ever be null. So any mod that assumes it is not null here would fail the same way. However, not many mods look up another block's item for displaying an item tooltip.

About the root cause, I have no idea. I'd need to either decompile, read and understand the AE2 code (thank but no thanks; that'd take days) or have a way to reproduce the problem in my development environment with an attached debugger.

**Comment by superpatosainz** [comment]
@HenryLoenwind oh god yea it'll take a fair amount of effort.

Btw AE2 isn't closed source lol <https://github.com/AppliedEnergistics/Applied-Energistics-2>

**Comment by HenryLoenwind** [comment]
Oops, I didn't even think to check. Thanks!
