### ISSUE TITLE
Add Dark Steel as a casting material for Tinker's Construct

### ISSUE THREAD

**Issue by codewarrior0** [CrazyPants/EnderIO#2009]
This would allow hoes, lumber axes, cleavers, arrows/bolts and other tools to be made from dark steel. I've done a tiny bit of work on TiCon's code and I would be willing to do some preliminary coding for this. It could be done via IMC calls to TiCon, which I've seen a few other mods do. Let me know if it's something you would like to add. I'm thinking Dark Steel would be just a half-step better than regular Steel. Maybe EIO's other metals could be usable in casting too?

**Comment by Adaptivity** [comment]
ExtraTiC will do it in future. So, it doesn't required to be done on Ender IO side.

**Comment by codewarrior0** [comment]
I see. I haven't read any news about that. However, since ExtraTiC isn't open source, if I wanted to add it myself I would end up doing it on the EIO side (or maybe TiC's side, or even by making an additional mod just to call between the two of them). 

ExtraTiC is also more tightly integrated with TiCon, meaning it calls TiCon's registry functions directly instead of using IMC. Whenever new tools or parts are added to TiCon, ETiC requires an update. And it looks like it hasn't been updated in six months...?

**Comment by Adaptivity** [comment]
Yes, it hasn't been updated in six months but the update is in progress. However, ExtraTiC doesn't required to be updated each TiC update, you just can't make new parts added by new TiC update but you can continue playing. You can see sneak peaks on MCF thread or here: https://twitter.com/JeanGlassmaker And yes, there are private beta exist which already has Dark Steel integration. So, adding this to Ender IO just waste your time.
