### ISSUE TITLE
cofh folder in EnderIO.jar?

### ISSUE THREAD

**Issue by Robijnvogel** [CrazyPants/EnderIO#2010]
Should there still be a cofh folder in enderIO.jar?
COFH doesn't support that anymore, right?

**Comment by Vexatos** [comment]
The folder is meant to be there.

**Comment by Robijnvogel** [comment]
Ok, I was just asking because this cofh folder causes incompatibility with COFHCore in some other mods. EnderIO does not have this problem yet, but prevention is better than cure.
