### ISSUE TITLE
Activated electromagnet glitches out minechem GUIs

### ISSUE THREAD

**Issue by akvgergo** [CrazyPants/EnderIO#2020]
^The title says it.
magnet on:
![2015-02-27_23 06 24](https://cloud.githubusercontent.com/assets/8812148/6422270/ecb57a6c-bed6-11e4-8595-bfa6e32dbf8a.png)
Magnet off:
![2015-02-27_23 06 15](https://cloud.githubusercontent.com/assets/8812148/6422272/f63e8ab0-bed6-11e4-82b7-534d976fb592.png)
using the Material energy^4 modpack
EIO: 2.2.6.317
minechem: 5.0.5.387 (beta version from the minechem build server, but same result with public version)

**Comment by akvgergo** [comment]
FYI no clue if this is on EIO's side or on minechem's, so I made a bug report for both Github pages.

**Comment by 6210classick** [comment]
you are using old version of EIO update to the latest and see if the problem still occurs

**Comment by tterrag1098** [comment]
The only difference between the magnet rendering when it is on vs off is the enchantment glint. Seems (to the surprise of no one) that MC is leaking GL states in its render. This is indeed a minechem "bug" in that they need to repair the GL state before rendering their tabs. 

As it has nothing to do with EIO code this is not our issue.
