### ISSUE TITLE
2 bugs (Repairing leggings, repairing anvil)

### ISSUE THREAD

**Issue by Teleclast** [CrazyPants/EnderIO#2021]
Having 2 bugs here
1)Cannot repair my dark pants, doing so crashes me with this report log:
http://pastebin.com/UhpDWfnf
This can be ignored, I'm fairly sure it's due to an enchant removed in newest version of Infinity, I was able to recreate same bug with enchanting table.

2)Attempting to repair the dark steel anvil (I thought that could be the issue) doesn't work on either an original anvil, or another dark steel anvil I created for this purpose. (I also tried 1st issue on both anvils)

**Comment by tterrag1098** [comment]
Your dark leggings have some corrupted enchantment data on them, that causes this crash when placed into the anvil. The crash is in vanilla control and EIO has no control over it. To fix I would delete the item and spawn in a new one.
