### ISSUE TITLE
crashbug thermal dynamics

### ISSUE THREAD

**Issue by leftyde** [CrazyPants/EnderIO#2023]
after I put a flux plated fluiduct next to a stirling generator, game & server crash with:
http://pastebin.com/GkwsiN4t

have installed:
EnderIO-1.7.10-2.2.8.349
CoFHCore-[1.7.10]3.0.0RC2-201
ThermalDynamics-[1.7.10]1.0.0RC2-89
ThermalExpansion-[1.7.10]4.0.0RC2-131
ThermalFoundation-[1.7.10]1.0.0RC3-57

**Comment by leftyde** [comment]
It seems that it has something to do with the new dual ducts (Flux plated fluiduct is RF and Fluids), because this does work:
http://imgur.com/tdK44Kk

**Comment by tterrag1098** [comment]
This is due to a mod in your environment having an outdated RF API, not EIO's fault.
