### ISSUE TITLE
MFR crash on startup 

### ISSUE THREAD

**Issue by orang3eagle** [CrazyPants/EnderIO#2024]
http://pastebin.com/swbgH3AB
Upon startup of client the mod does not render conduit bundle class files and have not found a way to correct this . up until today(2-28-15) the client worked well few if any crashes upon adding thermal dynamics the game stopped working

**Comment by HenryLoenwind** [comment]
See #1981 #1982 #1983 #1985 #1988 #1989 #1993 #1997 #2004 #2006 #2016
