### ISSUE TITLE
Crash report - conduit facades

### ISSUE THREAD

**Issue by DCBond** [CrazyPants/EnderIO#2025]
DCBond commented 2 minutes ago
Hello, I recently tried to paint a conduit facade using a TE Hardened Cache... Just to see if I could. It worked, so I foolishly attempted to place it on an item conduit. It crashed my game immediately. Now every time I log in to the server, I crash before I even see the game beyond the loading screen. My brother was on the server, playing just fine, when he went to attempt to break said conduit. As soon as he looked at it, his game crashed as well. Neither one of us can log in at all now.

Here's the crash report: http://pastebin.com/cujhvDBN

Any help or advice would be greatly appreciated!

**Comment by 6210classick** [comment]
delete it with MC edit , you shouldn't paint facades to look like machines or storage items

**Comment by tterrag1098** [comment]
This is already reported under the crash with binnie's facades (It's the same root issue) and has been resolved in the dev builds.
