### ISSUE TITLE
Visual Bug with Mekanism and gas conduits

### ISSUE THREAD

**Issue by crunkazcanbe** [CrazyPants/EnderIO#2036]
The gas conduit appears to not connect to the Chemical Oxidizer , but in reality it is connected .
Using EnderIO version 2.2.8.353 . I have tried re-logging , and still the same thing .

https://imgur.com/7KnN9Ge

**Comment by crunkazcanbe** [comment]
Also i want to say i do not have/use optifine.

**Comment by tterrag1098** [comment]
Then Mekanism is breaking its own API and not providing an IGasHandler from that block. Therefore EIO has no idea it exists. Our code does work, see the other blocks it is connecting to.
