### ISSUE TITLE
Null pointer exception, when placing ME conduit on an item conduit, EIO 1.7.10_2.2.8.344

### ISSUE THREAD

**Issue by Ronzan** [CrazyPants/EnderIO#2039]
CTD when placing an ME conduit on an item conduit.
EnderIO version: 2.2.8 344
AE2 version: rv2-beta-8
Crash log: http://pastebin.com/zKiaXWnC

Also issued here: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/963

**Comment by MatthiasMann** [comment]
That is fixed in 2.2.8 build 349 which is available on Curse

**Comment by Ronzan** [comment]
Cool, thanks :)
