### ISSUE TITLE
Me conduit world crash.-- solved, update into AE-RV2

### ISSUE THREAD

**Issue by CreamAle** [CrazyPants/EnderIO#2042]
ender io's cable caused instant crash upon placing it. was starting a new system, so the cable wasn't in contact with any other block other than vanilla bricks.

i tried disabling me conduits in the enderio config but it didnt help. removing the item from the world would fix the crash i feel.. although i dont know how to remove it as MCedit (from mcedit.net) doesnt delete blocks for some reason.

[Pastebin crash log](http://pastebin.com/7Z6CZ0t4)

applied energistics 2-rv1-stable-1
EnderIO-1.7.10 -2.2.8.349

**Comment by Adaptivity** [comment]
#1626 #1680 #1720 #1725 #1730 #1792 #1795 #1796 #1813 #1898 #1910 #1911 #1938 #2000

**Comment by CreamAle** [comment]
i'll try downgrading into an older version just so i can fix this issue. then either keep the older version or update..

i'll post results.

**Comment by MatthiasMann** [comment]
You have to use EnderIO 2.2.8 build 349 or later together with AE2 rv2.

**Comment by CreamAle** [comment]
yep fixed already, also changed title to reflect solution.
