### ISSUE TITLE
Updated to 2.2.8.349, OpenComputers now reads data for a single capacitor rather than the entire multiblock

### ISSUE THREAD

**Issue by Sanwi** [CrazyPants/EnderIO#2043]
I'm using OpenComputers to monitor and control my power system, and it is no longer reading the data for the entire capacitor bank; just the block the adapter is connected to.

**Comment by Vexatos** [comment]
Are you sure you have the latest version of Computronics installed? Otherwise it will do exactly this.

**Comment by Sanwi** [comment]
Thanks! I think that was the issue. I'm on a multiplayer server, so I'm not able to just change the mods myself. They're using 1.4.0 instead of 1.4.2, so I reported it.
