### ISSUE TITLE
Mouse Wheel Scroll

### ISSUE THREAD

**Issue by Cracks777** [CrazyPants/EnderIO#2049]
enderio is blocking all other mods from using Mouse Scroll Wheel? there are other mods that cant use the scroll wheel because enderio. is there something that can be done?

**Comment by Cracks777** [comment]
https://github.com/micdoodle8/Galacticraft/issues/1397#issuecomment-77066520

heres why.

**Comment by HenryLoenwind** [comment]
@tterrag1098 Our complete wheel handling code seems to be based on wrong assumptions. It basically does:

    x = wheel /120; wheel = 0;
    if (x != wheel) {
        wheel = 0;
        diff = x - wheel;
        wheel = 0;
        if (diff < 0) ... else if (diff > 0) else NOP
    ...

I can have a look at this in the evening, if it's ok with you.
