### ISSUE TITLE
Client Crash 

### ISSUE THREAD

**Issue by DrakeBD** [CrazyPants/EnderIO#2050]
Crashed While been around EnderIO Machines

can find the crash report file here https://dl.dropboxusercontent.com/u/38820381/crashlogs/DrakeBD%20Ender%20IO%20Bug.txt

**Comment by tterrag1098** [comment]
EnderIO does not support the use of Optifine (and it is probably the cause
of your crash)

**Comment by DrakeBD** [comment]
No offence but that's rubbish as EnderIO works perfectly fine single player the crash occurs when EnderIO is on a dedicated server then the clients crash with that report but single player all machines and cables work as intended with optifine installed

**Comment by tterrag1098** [comment]
Then prove it to me. Remove optifine from your client and reproduce the
crash.

**Comment by DrakeBD** [comment]
Its simple the crash only occurs when you use EnderIO machines and cables on a Dedicated server not on single player so how exactly would optifine cause this issue ......

But its ok if you don't want to look into it and just blame optifine fair enough we have fixed the issue by removing the mod from the server and client.

**Comment by tterrag1098** [comment]
You're not listening to me. I see optifine in your stacktrace and that is reason enough for me to believe it is the cause of a *RENDERING* related issue. If you can simply remove optifine from your client and reproduce this crash, I will look into it. But I am fairly sure you will not be able to do that.

**Comment by DrakeBD** [comment]
I am listening but as we need optifine its removal is not optional.

**Comment by tterrag1098** [comment]
Optifine should never be used in a molded environment. Why do you "need" it?

**Comment by DrakeBD** [comment]
We produce Texture Packs so require it for connected textures support and performance.
if it was not ment to be in a modded environment it would not be a forge mod itself and all other mods work fine with it it was just this one that had a spaz attack. on the server but totally fine in single player or even on a LAN
