### ISSUE TITLE
SAGMill Recipes-Group "Common Ores/Ingots" can't be disabled

### ISSUE THREAD

**Issue by braeven** [CrazyPants/EnderIO#2078]
I'm testing around with changing recipes and was able to disable all other SAGmill related recipes-groups(like Vanilla, EnderIO, Dense Ores, ...) , but all recipes in the group "Common Ores/Ingots" can't be deactivated.

Yes I replaced the SAGMillRecipes_User.xml and was using this code:

```
<SAGMillRecipes>
<recipeGroup name="Vanilla" enabled="false"/> 
<recipeGroup name="Dense Ores" enabled="false"/>
<recipeGroup name="Common Ores/Ingots" enabled="false"/>
<recipeGroup name="Biomes O' Plenty" enabled="false"/>
<recipeGroup name="EnderIO" enabled="false"/>
<recipeGroup name="Applied Energistics" enabled="false" />
</SAGMillRecipes>
```

Could it be, that the "/" in the name of the group is resposibility for this problem?

Also tested it on some modpack like FTB Infinity, direwolf 20, infitech2 with different ender-io version, same result.

Relevant Mods:
EnderIO-1.7.10-2.2.8.349
Forge 10.13.2.1307-1.7.10
(of course there are more mods, but they shouldn't interfere with enderio)

**Comment by 6210classick** [comment]
if you disabled EnderIO & Vanilla & Common Ores recipes shouldn't that render the Sagmill useless ? maybe it's intended that way as a fail-safe ?

**Comment by braeven** [comment]
I tried to disable everything else cause I was thinking I made a mistake, it's just for testing purposes.

Don't know if it's a failsafe, but I'm trying to change the way ore's are processed, so I don't want them to be 1 ore -> 2 dust(+more), so I need to disable or change the default-recipes to archive this.

Also tried to replace the default-recipes with empty-one(like it's written in the user file) didn't work also for this group

**Comment by 6210classick** [comment]
post the recipe you want to replace and mods that adds the ingots i will try to see if i can do it

**Comment by braeven** [comment]
I was trying to change the recipe for Copper-Ore/Dust(and would have changed the other ores) but the bug appeared

Mods that add Copper-Ore
Cofh/Thermal Foundation
Tinkers' Construct
(and I use aobd and activated clusters und dirty dust)

Codes I used:
```
<recipeGroup name="Common Ores/Ingots">
      <recipe name="CopperOre2" energyCost="3600">
      <input>
        <itemStack oreDictionary="plankWood" />
      </input>      
      <output>
        <itemStack modID="aobd" itemName="clusterCopper" number="1" />
        <itemStack modID="aobd" itemName="dustDirtyCopper" number="1" chance="0.10" />
      </output>
    </recipe>

      <recipe name="CopperOre3" energyCost="3600">
      <input>
        <itemStack oreDictionary="oreCopper" />
      </input>      
      <output>
        <itemStack modID="aobd" itemName="clusterCopper" number="1" />
        <itemStack modID="aobd" itemName="dustDirtyCopper" number="1" chance="0.10" />
      </output>
    </recipe>

      <recipe name="CopperOre" energyCost="3600">
      <input>
        <itemStack oreDictionary="oreCopper" />
      </input>      
      <output>
        <itemStack modID="aobd" itemName="clusterCopper" number="1" />
        <itemStack modID="aobd" itemName="dustDirtyCopper" number="1" chance="0.10" />
      </output>
    </recipe>
</recipeGroup> 
```
The recipe named CopperOre2 which makes copper out of planks does work
The recipes named CopperOre(which would override the recipe in the core.xml) and CopperOre3 don't work and they are only modified copies of the CopperOre2-Recipe.

It also doesn't matter if I create a new recipe-group, I can't change the original Recipe

**Comment by 6210classick** [comment]
i might be stupid or missing something , when i go to AOBD tab in creative there is nothing in it . how i can add clusterCopper & dustDirtyCopper ?

i'm using
Mantle-1.7.10-0.3.2
CoFHCore-[1.7.10]3.0.0RC5-207
TConstruct-1.7.10-1.8.2a
ThermalFoundation-[1.7.10]1.0.0RC4-58
ThermalExpansion-[1.7.10]4.0.0RC6-138
EnderIO-1.7.10-2.2.8.349
FORGE 1291

**Comment by braeven** [comment]
you need to change the config for aodb, there is an entry for this:
```
    # Add prefixes separated by commas.
    # Textures will be aobd:prefix and aobd:prefix_overlay.
    # Example: dust,cluster
    S:items= dust, dustDirty, cluster
```

**Comment by 6210classick** [comment]
i see your problem now  , Common Ores/Ingots group cannot be disabled , it so weird it just can't be disabled i even managed to edit the core.xml and changes was saved but it still can't get disabled , deleted the entire ''Common Ores/Ingots group'' from the core.xml

to do that edit Sagmill_core.XML and remove ''Common Ores/Ingots group'' then save it next open EIO jar file with winrar then go to assets > config and drag your modified core.xml to it

then delete core.xml in EIO Config file the new generated will be the one you have modified

sorry bro i couldn't be much of help i really want to get it working too i never knew what AOBD was until i start messing with it , and gotta say i love the cluster & dirty cluster if you manage to get it working plz do let me know

**Comment by braeven** [comment]
Did some testing and even after editing the .jar and deleting the recipes, the recipes didn't disappear.

I started rebuilding my modpack part by part (adding one mod, starting it up and look if it's working like intendet) and found out that it is AOBD interfering with the Sag Mill:
AOBD automatically detects every ore and adds processing-recipes to the sag-mill and overrites all my changes. To prevent this, you have to edit the config for AOBD and disable enderio for every ore.

Problem solved.

**Comment by 6210classick** [comment]
what an easy solution for a complicated issue , so can common ores group be disabled now ?

**Comment by MatthiasMann** [comment]
The _user.xml can disable / change all recipes from the _core.xml - the issue is that IMC based recipes (eg these done by AOBD and other mods) are executed after the _user.xml has been processed.
