### ISSUE TITLE
Removing Paintings

### ISSUE THREAD

**Issue by aiventimptner** [CrazyPants/EnderIO#2081]
It would be awesome to have the opportunity to remove paintings from painted Blocks.

**Comment by MatthiasMann** [comment]
You can just repaint them as often as you want

**Comment by aiventimptner** [comment]
Yeah i know, but when i got so many different types of paintings and want them to stack. That won't work well ...

**Comment by MatthiasMann** [comment]
Just paint them as one of the things you have most of - eg I mostly store conduit facades as stone bricks or chisel's large cobblestone tiles. That way they easily stack.

**Comment by aiventimptner** [comment]
Yes you're right, I also do this. But if I painted e.g. a Travel Anchor, than i can't get the default look back.

**Comment by MatthiasMann** [comment]
I think you can just paint it with a travel anchor :)

**Comment by aiventimptner** [comment]
Really?! That would be great. I will try it later.
