### ISSUE TITLE
Wrench not working since fix #2053

### ISSUE THREAD

**Issue by emperor06** [CrazyPants/EnderIO#2082]
I don't know what's going on (if it's only me or not) but I have wrench issues since commit b1efc0d8feebff4971c5fa6c38e004e9e299eaac (Refactor how block drops work. Now relies on getDrops.)
I just can't wrench any EIO machine with a Yeta wrench anymore. A normal right-click still works (I can set the machine sides) but a shift-click fails to dismantle any tile entity. It works perfectly fine on previous commits and still bugs for me up to the very last commit.

It puzzles me because at the same time:
- Yeta wrench fails to work with any Mekanism things but works with any AE2 tile entities and parts.
- Mekanism's Configurator (wrench mode) and AE2's certus wrench/network reader can't wrench EIO's entities as well.
- as stated, the Yeta wrench still works on conduits.
So I don't know if it's an issue with some dependencies or with the mod itself.

Using:
- MC 1.7.10
- forge 10.13.2.1291
- Mekanism and AE2 both compiled from the latest commit (so AE2 is rv2, I think EIO uses rv1's API)
- NEI, Waila, CodeChickenCore, all on latest version
- gradle 2.3 and java 1.7.0_60

Building:
git checkout b1efc0d8feebff4971c5fa6c38e004e9e299eaac
gradle clean build

I tried with --refresh-dependencies as well but it still bugs.

**Comment by MatthiasMann** [comment]
EnderIO requires AE2 rv2 or later - rv1 is not binary compatible with rv2 - that's why rv1 support was dropped long ago:
https://github.com/CrazyPants/EnderIO/blob/master/ReleaseNotes.txt#L127

**Comment by emperor06** [comment]
That's what I thought. I was not 100% sure because I have a gradle.properties file that still references rv1 (ae2_version=rv1-stable-1) but yeah, the rv2 api is shipped in src/java/api/appeng anyway.

I just tried with EIO alone (no other mod but forge) and I still can't wrench anything. The last thing I have to check is to use the provided gradle wrapper.

**Comment by tterrag1098** [comment]
Tracking via #2086
