### ISSUE TITLE
[Suggestion] Existing Item Filter Active/ Passive

### ISSUE THREAD

**Issue by Bordissed** [CrazyPants/EnderIO#2087]
I don't know for sure if anyone has already asked for this, but it's the kind of thing that makes a huge difference...

I would like the existing item filter to have a passive/active option, where Passive makes it so you have to take a snapshot everytime you want the filter to change, and Active makes the filter update everytime the inventory next to it recieves a new item by the player. 

This way it would be possible to (for example) have a chest just for raw ores and everytime you wished to add or divert the flow of ores to somewhere else (say, a grinder) you could just do it by placing or removing ores from their chest.

There are many applications, this is also quite useful when doing sorting mechanisms since you can just add newly discovered items to a system simply by placing them on chests.
Overall makes things more dynamic.

Here's hoping this will get implemented!
Bordissed

**Comment by MatthiasMann** [comment]
When you clear the snapshot of the existing item filter it will use the current inventory content as filter.
