### ISSUE TITLE
Vibrant Capacitor Bank Bug

### ISSUE THREAD

**Issue by Dinale54** [CrazyPants/EnderIO#2089]
I had six vibrant capacitor banks setup, a creeper sneaks up behind me and blows everything up. When I start cleaning up the area, I notice that all of the capacitor banks dropped as creative capacitor banks, not vibrant. This happened on a multiplayer server running the current recommended version of FTB Infinity.

**Comment by 6210classick** [comment]
yep it's been fixed in dev versions while you at it just enjoy unlimited power or get rid of them your choice

**Comment by tterrag1098** [comment]
This is fixed and a dupe issue
