### ISSUE TITLE
Dupe Bug

### ISSUE THREAD

**Issue by Loreithiel** [CrazyPants/EnderIO#2092]
When using the SAG Mill, if you put an item in the input area and then take it out it continues to grind the item, producing the dusts and items you would get, but you also keep what you had originally put in.

**Comment by tterrag1098** [comment]
Version? Screenshots? What item? This is a very serious bug if true, but no one else has ever reported it.

**Comment by Loreithiel** [comment]
After further looking into it, I discovered that it was not bug. The SAG Mill removes the item from the input, then starts grinding it, unlike the regular vanilla furnace. Because I had items constantly feeding into it, it caused me to believe that the items were being duped. Sorry about this.
