### ISSUE TITLE
Suggestion: Photovoltaic Arrays

### ISSUE THREAD

**Issue by ghost** [CrazyPants/EnderIO#504]
Basically blocks similar to compact solars lv, mv, and hv arrays, except using photovoltaic cells instead of solar panels.

Perhaps the recipe should be a 8 photovoltaic cells + machine chassi = Photovoltaic array, which produces 8x the base value set in the config for the photovoltaic cell.

Second tier should be using 8 of that array + machine chassi = Condensed Photovoltaic Array (or whatever name you choose) and this produces 64x the base value set in the config for the photovoltaic cell.

Maybe a third tier (using 8 condensed arrays + machine chassi)  that produces 512x the base value set in the config.

A good reason to implement this is because having setups with a lot of arrays (100+) can be very bad for servers as they all tick and use up server tick time which can cause a tps drop. Having a condensed array will be a good way to use solar energy without having to worry about lag caused because of giant setups of multiple cells.

**Comment by tterrag1098** [comment]
Yes, it is.
